extends Control

# IMMUNE DEFENSE PROTOCOL — pixel-art card-draft quest.
# Draft 5 immune cells to counter 5 invading pathogens, then deploy and score.
# All art is generated by tools/make_immune.py into assets/generated/immune/.

const CARD_SCENE := preload("res://scenes/card.tscn")
const ART := "res://assets/generated/immune/"
const FONT_PATH := "res://art/Dialogue/determination.ttf"
const DATA_PATH := "res://art/text_resources/immune_cards_data.json"
const RETURN_SCENE := "res://scenes/TitleScreen.tscn"

var battle_manager = preload("res://scripts/battle_manager.gd").new()

# ---- node refs --------------------------------------------------------------
@onready var background_layer: TextureRect = $BackgroundLayer
@onready var top_bar: Panel = $TopBar
@onready var title_label: Label = $TopBar/TitleLabel
@onready var enemy_zone: Panel = $MainArea/EnemyZone
@onready var enemy_title: Label = $MainArea/EnemyZone/EnemyVBox/EnemyTitle
@onready var enemy_cards_container: GridContainer = $MainArea/EnemyZone/EnemyVBox/EnemyScroll/EnemyCards
@onready var deck_zone: Panel = $MainArea/DeckZone
@onready var deck_title: Label = $MainArea/DeckZone/DeckVBox/DeckTitle
@onready var deck_cards_container: GridContainer = $MainArea/DeckZone/DeckVBox/DeckScroll/DeckCards
@onready var bottom_bar: Panel = $BottomBar
@onready var drafted_label: Label = $BottomBar/DraftedLabel
@onready var drafted_cards_container: HBoxContainer = $BottomBar/DraftedCards
@onready var start_button: Button = $BottomBar/StartBattleButton

@onready var results_overlay: Control = $ResultsOverlay
@onready var results_panel: Panel = $ResultsOverlay/ResultsPanel
@onready var results_stars_row: HBoxContainer = $ResultsOverlay/ResultsPanel/MarginContainer/VBoxContainer/StarsRow
@onready var results_title: Label = $ResultsOverlay/ResultsPanel/MarginContainer/VBoxContainer/TitleLabel
@onready var results_score_label: Label = $ResultsOverlay/ResultsPanel/MarginContainer/VBoxContainer/ScoreLabel
@onready var analysis_label: Label = $ResultsOverlay/ResultsPanel/MarginContainer/VBoxContainer/AnalysisLabel
@onready var matchups_container: VBoxContainer = $ResultsOverlay/ResultsPanel/MarginContainer/VBoxContainer/MatchupsScroll/MatchupsContainer
@onready var retry_button: Button = $ResultsOverlay/ResultsPanel/MarginContainer/VBoxContainer/ButtonsContainer/RetryButton
@onready var continue_button: Button = $ResultsOverlay/ResultsPanel/MarginContainer/VBoxContainer/ButtonsContainer/ContinueButton

var all_pathogens: Array = []
var all_immune_cells: Array = []
var current_pathogens: Array = []
var drafted_team: Array = []
var drafted_card_nodes: Array = []
var deck_card_nodes: Array = []
const MAX_TEAM_SIZE := 5

var _tex := {}
var _drafted_slots: Array = []   # the 5 empty-slot panels in the bottom bar


# =============================================================================
func _ready() -> void:
	add_child(battle_manager)
	_load_textures()
	_apply_skin()
	load_card_data()
	setup_game()
	_build_drafted_slots()

	start_button.pressed.connect(_on_start_battle)
	continue_button.pressed.connect(_on_continue_clicked)
	retry_button.pressed.connect(_on_retry_clicked)
	start_button.disabled = true
	results_overlay.visible = false
	update_drafted_label()
	_intro_anim()


# ---- pixel skin -------------------------------------------------------------
func _load_textures() -> void:
	for n in ["bg", "frame_panel", "frame_pathogen", "frame_immune", "frame_window",
			"frame_banner", "frame_slot", "button", "star_full", "star_empty",
			"badge_perfect", "badge_good", "badge_bad", "badge_neutral"]:
		var p: String = ART + n + ".png"
		_tex[n] = load(p) if ResourceLoader.exists(p) else null


func _apply_skin() -> void:
	# every label/button inherits the game's determination pixel font
	var th := Theme.new()
	if ResourceLoader.exists(FONT_PATH):
		th.default_font = load(FONT_PATH)
	th.default_font_size = 16
	theme = th

	if background_layer:
		background_layer.texture = _tex.get("bg")

	top_bar.add_theme_stylebox_override("panel", _frame_box("frame_banner", 6))
	enemy_zone.add_theme_stylebox_override("panel", _frame_box("frame_pathogen", 4))
	deck_zone.add_theme_stylebox_override("panel", _frame_box("frame_immune", 4))
	bottom_bar.add_theme_stylebox_override("panel", _frame_box("frame_panel", 4))
	results_panel.add_theme_stylebox_override("panel", _frame_box("frame_window", 6))

	title_label.add_theme_color_override("font_color", Color("ffe08a"))
	title_label.add_theme_color_override("font_outline_color", Color("1a1206"))
	title_label.add_theme_constant_override("outline_size", 5)
	enemy_title.add_theme_color_override("font_color", Color("ff9a9a"))
	deck_title.add_theme_color_override("font_color", Color("8fd0f0"))
	drafted_label.add_theme_color_override("font_color", Color("cfe0ea"))
	results_title.add_theme_color_override("font_color", Color("ffe08a"))
	analysis_label.add_theme_color_override("font_color", Color("ffe08a"))

	_style_button(start_button, Color("2f9e5a"))
	_style_button(retry_button, Color("3a78a8"))
	_style_button(continue_button, Color("2f9e5a"))


func _build_drafted_slots() -> void:
	# five recessed placeholder slots so the team bar reads as a deck, not blank.
	for i in range(MAX_TEAM_SIZE):
		var slot := Panel.new()
		slot.custom_minimum_size = Vector2(118, 150)
		slot.add_theme_stylebox_override("panel", _frame_box("frame_slot", 0, 4))
		slot.mouse_filter = Control.MOUSE_FILTER_IGNORE
		var hint := Label.new()
		hint.text = str(i + 1)
		hint.set_anchors_preset(Control.PRESET_FULL_RECT)
		hint.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
		hint.vertical_alignment = VERTICAL_ALIGNMENT_CENTER
		hint.add_theme_font_size_override("font_size", 40)
		hint.add_theme_color_override("font_color", Color(1, 1, 1, 0.10))
		slot.add_child(hint)
		drafted_cards_container.add_child(slot)
		_drafted_slots.append(slot)


func _refresh_slots() -> void:
	for i in range(_drafted_slots.size()):
		_drafted_slots[i].visible = i >= drafted_team.size()


# =============================================================================
#  Data + setup
# =============================================================================
func load_card_data() -> void:
	var file := FileAccess.open(DATA_PATH, FileAccess.READ)
	if file == null:
		push_error("Could not open " + DATA_PATH)
		return
	var json := JSON.new()
	if json.parse(file.get_as_text()) == OK:
		var data = json.data
		all_pathogens = data.pathogen_cards
		all_immune_cells = data.immune_cards
	else:
		push_error("Error parsing immune card data JSON")
	file.close()


func setup_game() -> void:
	current_pathogens = []
	var pool: Array = all_pathogens.duplicate()
	pool.shuffle()
	for i in range(min(5, pool.size())):
		current_pathogens.append(pool[i])
	display_pathogens()
	display_immune_deck()


func display_pathogens() -> void:
	for pathogen in current_pathogens:
		var card = CARD_SCENE.instantiate()
		enemy_cards_container.add_child(card)
		card.setup_pathogen(pathogen)


func display_immune_deck() -> void:
	for immune_cell in all_immune_cells:
		var card = CARD_SCENE.instantiate()
		deck_cards_container.add_child(card)
		card.setup_immune(immune_cell)
		card.card_clicked.connect(_on_immune_card_clicked)
		deck_card_nodes.append(card)


# =============================================================================
#  Drafting
# =============================================================================
func _on_immune_card_clicked(card) -> void:
	var idx := -1
	for i in range(drafted_team.size()):
		if drafted_team[i].id == card.card_data.id:
			idx = i
			break

	if idx >= 0:
		drafted_team.remove_at(idx)
		var node = drafted_card_nodes[idx]
		drafted_card_nodes.remove_at(idx)
		node.queue_free()
		card.set_selected(false)
		update_drafted_label()
		start_button.disabled = true
	elif drafted_team.size() < MAX_TEAM_SIZE:
		drafted_team.append(card.card_data)
		card.set_selected(true)
		create_drafted_card(card.card_data)
		update_drafted_label()
		if drafted_team.size() == MAX_TEAM_SIZE:
			start_button.disabled = false
			_pulse(start_button)
	_refresh_slots()


func create_drafted_card(card_data: Dictionary) -> void:
	var drafted_card = CARD_SCENE.instantiate()
	# insert before the remaining placeholder slots so cards fill left-to-right
	var insert_at: int = drafted_team.size() - 1
	drafted_cards_container.add_child(drafted_card)
	drafted_cards_container.move_child(drafted_card, insert_at)
	await get_tree().process_frame
	drafted_card.set_compact(true)
	drafted_card.setup_immune(card_data)
	drafted_card.is_clickable = true
	drafted_card.mouse_filter = Control.MOUSE_FILTER_STOP
	drafted_card.card_clicked.connect(_on_drafted_card_clicked)
	drafted_card_nodes.append(drafted_card)
	_pop_in(drafted_card)


func _on_drafted_card_clicked(drafted_card) -> void:
	var idx := -1
	for i in range(drafted_card_nodes.size()):
		if drafted_card_nodes[i] == drafted_card:
			idx = i
			break
	if idx < 0:
		return
	var card_data = drafted_team[idx]
	drafted_team.remove_at(idx)
	drafted_card_nodes.remove_at(idx)
	drafted_card.queue_free()
	for deck_card in deck_card_nodes:
		if deck_card.card_data.id == card_data.id:
			deck_card.set_selected(false)
			break
	update_drafted_label()
	start_button.disabled = true
	_refresh_slots()


func update_drafted_label() -> void:
	var remaining := MAX_TEAM_SIZE - drafted_team.size()
	if remaining > 0:
		drafted_label.text = "YOUR DEFENSE TEAM — select %d more cell%s" % [remaining, "" if remaining == 1 else "s"]
	else:
		drafted_label.text = "YOUR DEFENSE TEAM — ready to deploy!"


# =============================================================================
#  Battle + results
# =============================================================================
func _on_start_battle() -> void:
	if drafted_team.size() != MAX_TEAM_SIZE:
		return
	var results = battle_manager.calculate_battle_score(drafted_team, current_pathogens)
	show_results_screen(results)


func show_results_screen(results: Dictionary) -> void:
	# star sprites
	for child in results_stars_row.get_children():
		child.queue_free()
	var stars: int = results.stars
	for i in range(5):
		var s := TextureRect.new()
		s.texture = _tex.get("star_full") if i < stars else _tex.get("star_empty")
		s.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST
		s.custom_minimum_size = Vector2(40, 40)
		s.stretch_mode = TextureRect.STRETCH_KEEP_ASPECT_CENTERED
		results_stars_row.add_child(s)
		if i < stars:
			s.scale = Vector2.ZERO
			s.pivot_offset = Vector2(20, 20)
			var tw := s.create_tween().set_trans(Tween.TRANS_BACK).set_ease(Tween.EASE_OUT)
			tw.tween_interval(0.12 * i)
			tw.tween_property(s, "scale", Vector2.ONE, 0.32)

	results_title.text = "MISSION COMPLETE" if stars >= 3 else "BREACH CONTAINED"
	results_score_label.text = "Score  %d / %d" % [results.total_score, results.max_possible_score]
	var pct := float(results.total_score) / float(max(1, results.max_possible_score))
	var col := Color("ff8a5a")
	if pct >= 0.8:
		col = Color("6ee07a")
	elif pct >= 0.6:
		col = Color("ffe08a")
	results_score_label.add_theme_color_override("font_color", col)

	for child in matchups_container.get_children():
		child.queue_free()
	for m in results.matchup_details:
		matchups_container.add_child(_make_matchup_row(m))

	results_overlay.visible = true
	results_overlay.modulate = Color(1, 1, 1, 0)
	create_tween().tween_property(results_overlay, "modulate:a", 1.0, 0.25)


func _make_matchup_row(m: Dictionary) -> Control:
	var row := HBoxContainer.new()
	row.add_theme_constant_override("separation", 8)
	var badge := TextureRect.new()
	badge.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST
	badge.custom_minimum_size = Vector2(20, 20)
	badge.stretch_mode = TextureRect.STRETCH_KEEP_ASPECT_CENTERED
	badge.size_flags_vertical = Control.SIZE_SHRINK_CENTER
	var col := Color.WHITE
	match m.rating:
		"Perfect":
			badge.texture = _tex.get("badge_perfect"); col = Color("8ff0b0")
		"Good":
			badge.texture = _tex.get("badge_good"); col = Color("9ad0ff")
		"Bad":
			badge.texture = _tex.get("badge_bad"); col = Color("ff9aa6")
		_:
			badge.texture = _tex.get("badge_neutral"); col = Color("c2cdd6")
	row.add_child(badge)
	var lbl := Label.new()
	lbl.text = m.reason
	lbl.add_theme_color_override("font_color", col)
	lbl.add_theme_font_size_override("font_size", 15)
	lbl.autowrap_mode = TextServer.AUTOWRAP_WORD_SMART
	lbl.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	lbl.custom_minimum_size = Vector2(520, 0)
	row.add_child(lbl)
	return row


func _on_retry_clicked() -> void:
	get_tree().reload_current_scene()


func _on_continue_clicked() -> void:
	if ResourceLoader.exists(RETURN_SCENE):
		get_tree().change_scene_to_file(RETURN_SCENE)
	else:
		get_tree().reload_current_scene()


# =============================================================================
#  Juice
# =============================================================================
func _intro_anim() -> void:
	for n in [top_bar, enemy_zone, deck_zone, bottom_bar]:
		if n == null:
			continue
		n.modulate = Color(1, 1, 1, 0)
		create_tween().set_trans(Tween.TRANS_QUAD).tween_property(n, "modulate:a", 1.0, 0.35)


func _pop_in(node: Control) -> void:
	node.pivot_offset = node.custom_minimum_size * 0.5
	node.scale = Vector2(0.6, 0.6)
	var tw := node.create_tween().set_trans(Tween.TRANS_BACK).set_ease(Tween.EASE_OUT)
	tw.tween_property(node, "scale", Vector2.ONE, 0.22)


func _pulse(node: Control) -> void:
	node.pivot_offset = node.size * 0.5
	var tw := node.create_tween().set_loops(2).set_trans(Tween.TRANS_SINE)
	tw.tween_property(node, "scale", Vector2(1.06, 1.06), 0.18)
	tw.tween_property(node, "scale", Vector2.ONE, 0.18)


# =============================================================================
#  UI helpers (match the established pixel-quest style)
# =============================================================================
func _frame_box(frame_name: String, content_margin: int = 0, tmargin: int = 6) -> StyleBox:
	var tex: Texture2D = _tex.get(frame_name)
	if tex:
		var sb := StyleBoxTexture.new()
		sb.texture = tex
		sb.texture_margin_left = tmargin
		sb.texture_margin_top = tmargin
		sb.texture_margin_right = tmargin
		sb.texture_margin_bottom = tmargin
		sb.content_margin_left = content_margin
		sb.content_margin_right = content_margin
		sb.content_margin_top = content_margin
		sb.content_margin_bottom = content_margin
		return sb
	var f := StyleBoxFlat.new()
	f.bg_color = Color("12202b")
	f.border_color = Color("2f5d72")
	f.set_border_width_all(2)
	return f


func _button_box(col: Color) -> StyleBox:
	var tex: Texture2D = _tex.get("button")
	if tex:
		var sb := StyleBoxTexture.new()
		sb.texture = tex
		sb.modulate_color = col
		sb.texture_margin_left = 5
		sb.texture_margin_top = 5
		sb.texture_margin_right = 5
		sb.texture_margin_bottom = 5
		sb.content_margin_left = 16
		sb.content_margin_right = 16
		sb.content_margin_top = 9
		sb.content_margin_bottom = 9
		return sb
	var f := StyleBoxFlat.new()
	f.bg_color = col.darkened(0.15)
	f.border_color = col.lightened(0.25)
	f.set_border_width_all(2)
	return f


func _style_button(btn: Button, col: Color) -> void:
	btn.add_theme_stylebox_override("normal", _button_box(col))
	btn.add_theme_stylebox_override("hover", _button_box(col.lightened(0.16)))
	btn.add_theme_stylebox_override("pressed", _button_box(col.darkened(0.2)))
	btn.add_theme_stylebox_override("disabled", _button_box(col.darkened(0.5)))
	btn.add_theme_color_override("font_color", Color("f7fffb"))
	btn.add_theme_color_override("font_hover_color", Color("ffffff"))
	btn.add_theme_color_override("font_disabled_color", Color("9fb0bb"))
