extends Node2D
# =============================================================================
#  PRISM ARRAY  —  "The Art of Light"   ·  self-contained pixel-art laser puzzle
# =============================================================================
# A photonics-lab puzzle: a laser EMITTER fires a beam across an optical grid.
# Drop MIRRORS to bend it and PRISMS to recolour it, threading the light through
# every CRYSTAL so each lights in the colour it craves.  Three chambers of
# rising difficulty; the fewer pieces you use, the more of the 5 stars you keep.
#
# Built in the same house style as the NANOBOT SURGEON / IMMUNE / XENO remasters:
#   * all art generated by tools/make_laser.py -> assets/generated/laser/
#   * the determination pixel font on every label & button
#   * beveled 9-slice StyleBoxTexture panels & buttons, animated star sprites
#   * everything anchored inside 1152x648 (overlays via CenterContainer)
#
# Wiring: launched from Ashley's art house; records stars as laser_quest / "Art";
# returns to the ArtHouse when finished.
# =============================================================================

const ART := "res://assets/generated/laser/"
const FONT_PATH := "res://art/Dialogue/determination.ttf"

@export var return_scene: String = "res://scenes/maps/ArtHouse.tscn"
@export var quest_id: String = "laser_quest"
@export var domain: String = "Art"
var record_on_win := true                       # harness sets false

# ---- board geometry (sized to 1152x648) -------------------------------------
const GW := 12
const GH := 7
const CELL := 64
const BOARD := Rect2(192, 96, GW * CELL, GH * CELL)   # 768 x 448, centred

# ---- colour palette ---------------------------------------------------------
const COLORS := {
	"white":   Color("f4f7ff"),
	"red":     Color("ff4d5e"),
	"amber":   Color("ffb12e"),
	"green":   Color("46e35a"),
	"cyan":    Color("34e0ff"),
	"blue":    Color("5a7dff"),
	"magenta": Color("ff5ad0"),
}

# ---- chambers (each authored with a known solution for the verifier) --------
# dirs: R L U D ; mirror orient: "/" or "\\"
const CHAMBERS := [
	{
		"name": "FIRST LIGHT",
		"hint": "Bounce the beam off a mirror to pour it into the crystal.",
		"emitter": {"cell": Vector2i(0, 1), "dir": "R", "color": "cyan"},
		"walls": [Vector2i(5, 3), Vector2i(6, 3), Vector2i(2, 5)],
		"targets": [{"cell": Vector2i(8, 5), "color": "cyan"}],
		"prism_colors": ["cyan"],
		"mirrors": 4, "prisms": 0, "par": 1,
		"solution": [{"t": "mirror", "cell": Vector2i(8, 1), "o": "\\"}],
	},
	{
		"name": "PRISM SPLIT",
		"hint": "Light the red crystal, then refract the beam blue for the next.",
		"emitter": {"cell": Vector2i(0, 3), "dir": "R", "color": "red"},
		"walls": [Vector2i(2, 1), Vector2i(7, 5), Vector2i(7, 1)],
		"targets": [{"cell": Vector2i(4, 3), "color": "red"},
					{"cell": Vector2i(9, 5), "color": "blue"}],
		"prism_colors": ["blue", "red"],
		"mirrors": 4, "prisms": 3, "par": 2,
		"solution": [{"t": "prism", "cell": Vector2i(6, 3), "color": "blue"},
					 {"t": "mirror", "cell": Vector2i(9, 3), "o": "\\"}],
	},
	{
		"name": "THE GAUNTLET",
		"hint": "One beam, three crystals. Recolour as you weave it across the lab.",
		"emitter": {"cell": Vector2i(0, 0), "dir": "R", "color": "amber"},
		"walls": [Vector2i(3, 1), Vector2i(7, 4), Vector2i(8, 5), Vector2i(9, 2),
				  Vector2i(3, 5), Vector2i(10, 6), Vector2i(6, 5), Vector2i(7, 1)],
		"targets": [{"cell": Vector2i(2, 0), "color": "amber"},
					{"cell": Vector2i(3, 3), "color": "cyan"},
					{"cell": Vector2i(1, 6), "color": "magenta"}],
		"prism_colors": ["cyan", "magenta", "amber"],
		"mirrors": 6, "prisms": 4, "par": 5,
		"solution": [{"t": "mirror", "cell": Vector2i(5, 0), "o": "\\"},
					 {"t": "prism", "cell": Vector2i(5, 1), "color": "cyan"},
					 {"t": "mirror", "cell": Vector2i(5, 3), "o": "/"},
					 {"t": "mirror", "cell": Vector2i(1, 3), "o": "/"},
					 {"t": "prism", "cell": Vector2i(1, 5), "color": "magenta"}],
	},
]

enum Phase { INTRO, PLAY, INTERSTITIAL, VICTORY }

# ---- state ------------------------------------------------------------------
var _tex := {}
var _theme: Theme
var phase: int = Phase.INTRO
var level_index := 0
var elapsed := 0.0
var pieces_used_total := 0
var par_total := 0

var emitter_cell := Vector2i.ZERO
var emitter_dir := Vector2i.RIGHT
var emitter_color := "white"
var walls := {}                  # Vector2i -> true
var targets := []                # [{cell, color, lit, socket, gem, glow, _was}]
var pieces := {}                 # Vector2i -> {type, orient, color, node, glow}
var prism_palette := ["cyan"]

var tool := "mirror"
var mirrors_left := 0
var prisms_left := 0
var beam_segments := []          # [{a:Vector2, b:Vector2, c:Color}]
var has_hover := false
var hover_cell := Vector2i.ZERO
var hover_kind := "none"         # place / edit / blocked / nostock
var _primary: Callable = Callable()

# ---- nodes ------------------------------------------------------------------
var bg_layer: CanvasLayer
var world: Node2D
var tiles_root: Node2D
var optics_root: Node2D
var fx_root: Node2D
var beam_node: Node2D
var emitter_node: Sprite2D
var muzzle_glow: Sprite2D
var hud: CanvasLayer
var overlay: CanvasLayer
var toast: Label
var lbl_chamber: Label
var lbl_lit: Label
var btn_mirror: Button
var btn_prism: Button


# =============================================================================
func _ready() -> void:
	randomize()
	_load_textures()
	_theme = Theme.new()
	if ResourceLoader.exists(FONT_PATH):
		_theme.default_font = load(FONT_PATH)
	_theme.default_font_size = 18

	_build_background()
	world = Node2D.new()
	add_child(world)
	tiles_root = Node2D.new(); tiles_root.z_index = 0; world.add_child(tiles_root)
	beam_node = _Beam.new(); beam_node.quest = self; beam_node.z_index = 6; world.add_child(beam_node)
	optics_root = Node2D.new(); optics_root.z_index = 10; world.add_child(optics_root)
	fx_root = Node2D.new(); fx_root.z_index = 30; world.add_child(fx_root)

	_build_hud()
	_build_overlay()
	_show_intro()


func _load_textures() -> void:
	for n in ["bg", "frame_panel", "frame_window", "frame_banner", "button",
			"slot_off", "slot_on", "cell", "wall", "emitter", "mirror", "prism",
			"socket", "gem", "glow", "spark", "icon_mirror", "icon_prism",
			"icon_target", "star_full", "star_empty"]:
		var p: String = ART + n + ".png"
		_tex[n] = load(p) if ResourceLoader.exists(p) else null


# ---- construction -----------------------------------------------------------
func _build_background() -> void:
	bg_layer = CanvasLayer.new()
	bg_layer.layer = -10
	add_child(bg_layer)
	var tr := TextureRect.new()
	tr.texture = _tex.get("bg")
	tr.set_anchors_preset(Control.PRESET_FULL_RECT)
	tr.expand_mode = TextureRect.EXPAND_IGNORE_SIZE
	tr.stretch_mode = TextureRect.STRETCH_KEEP_ASPECT_COVERED
	tr.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST
	bg_layer.add_child(tr)


func cell_center(v: Vector2i) -> Vector2:
	return Vector2(BOARD.position.x + v.x * CELL + CELL * 0.5,
				   BOARD.position.y + v.y * CELL + CELL * 0.5)


func _in_grid(v: Vector2i) -> bool:
	return v.x >= 0 and v.x < GW and v.y >= 0 and v.y < GH


func _new_sprite(tex_name: String, pos: Vector2, parent: Node2D, z := 0,
		scale := 1.0) -> Sprite2D:
	var s := Sprite2D.new()
	s.texture = _tex.get(tex_name)
	s.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST
	s.position = pos
	s.z_index = z
	s.scale = Vector2(scale, scale)
	parent.add_child(s)
	return s


# =============================================================================
#  Level setup
# =============================================================================
func _clear_level() -> void:
	for c in tiles_root.get_children(): c.queue_free()
	for c in optics_root.get_children(): c.queue_free()
	for c in fx_root.get_children(): c.queue_free()
	targets.clear()
	pieces.clear()
	walls.clear()
	beam_segments.clear()
	emitter_node = null
	muzzle_glow = null


func _start_level(idx: int) -> void:
	level_index = idx
	var cfg = CHAMBERS[idx]
	_clear_level()

	# board tiles
	for r in range(GH):
		for c in range(GW):
			var v := Vector2i(c, r)
			_new_sprite("cell", cell_center(v), tiles_root, 0, CELL / 32.0)

	# walls
	for w in cfg.walls:
		walls[w] = true
		_new_sprite("wall", cell_center(w), tiles_root, 2, CELL / 32.0)

	# emitter
	emitter_cell = cfg.emitter.cell
	emitter_dir = _dir_vec(cfg.emitter.dir)
	emitter_color = cfg.emitter.color
	muzzle_glow = _new_sprite("glow", cell_center(emitter_cell), optics_root, 9, 0.7)
	muzzle_glow.modulate = COLORS[emitter_color]
	muzzle_glow.modulate.a = 0.85
	emitter_node = _new_sprite("emitter", cell_center(emitter_cell), optics_root, 11, CELL / 36.0 * 0.92)
	emitter_node.rotation = Vector2(emitter_dir).angle()

	# targets
	for t in cfg.targets:
		var pos := cell_center(t.cell)
		var glow := _new_sprite("glow", pos, optics_root, 7, 0.9)
		glow.modulate = COLORS[t.color]; glow.modulate.a = 0.0
		var socket := _new_sprite("socket", pos, optics_root, 8, CELL / 40.0 * 0.96)
		var gem := _new_sprite("gem", pos, optics_root, 9, CELL / 26.0 * 0.62)
		targets.append({"cell": t.cell, "color": t.color, "lit": false,
			"socket": socket, "gem": gem, "glow": glow, "_was": false})

	prism_palette = cfg.prism_colors
	mirrors_left = cfg.mirrors
	prisms_left = cfg.prisms
	tool = "mirror" if cfg.mirrors > 0 else "prism"
	phase = Phase.PLAY
	_update_targets_visual()
	_refresh_toolbar()
	lbl_chamber.text = "CHAMBER  %d / %d" % [idx + 1, CHAMBERS.size()]
	_flash_toast("%s" % cfg.name, 1.7, COLORS[emitter_color])


func _dir_vec(s: String) -> Vector2i:
	match s:
		"R": return Vector2i.RIGHT
		"L": return Vector2i.LEFT
		"U": return Vector2i.UP
		"D": return Vector2i.DOWN
	return Vector2i.RIGHT


# =============================================================================
#  Beam tracing
# =============================================================================
func _reflect(dir: Vector2i, orient: String) -> Vector2i:
	if orient == "/":
		match dir:
			Vector2i.RIGHT: return Vector2i.UP
			Vector2i.LEFT:  return Vector2i.DOWN
			Vector2i.UP:    return Vector2i.RIGHT
			Vector2i.DOWN:  return Vector2i.LEFT
	else:                                   # "\"
		match dir:
			Vector2i.RIGHT: return Vector2i.DOWN
			Vector2i.LEFT:  return Vector2i.UP
			Vector2i.UP:    return Vector2i.LEFT
			Vector2i.DOWN:  return Vector2i.RIGHT
	return dir


func _target_index(cell: Vector2i) -> int:
	for i in range(targets.size()):
		if targets[i].cell == cell:
			return i
	return -1


func _trace() -> void:
	for t in targets:
		t.lit = false
	beam_segments.clear()
	var cur := emitter_cell
	var dir := emitter_dir
	var col_name: String = emitter_color
	var seg_start := cell_center(cur)
	var guard := {}
	var steps := 0
	var maxsteps := GW * GH * 6
	while steps < maxsteps:
		steps += 1
		var nxt := cur + dir
		if not _in_grid(nxt):
			beam_segments.append({"a": seg_start, "b": cell_center(nxt), "c": COLORS[col_name]})
			return
		if walls.has(nxt):
			var face := cell_center(nxt) - Vector2(dir) * (CELL * 0.5)
			beam_segments.append({"a": seg_start, "b": face, "c": COLORS[col_name]})
			return
		if pieces.has(nxt):
			var pc = pieces[nxt]
			beam_segments.append({"a": seg_start, "b": cell_center(nxt), "c": COLORS[col_name]})
			if pc.type == "mirror":
				var key := "%d,%d|%d,%d" % [nxt.x, nxt.y, dir.x, dir.y]
				if guard.has(key):
					return
				guard[key] = true
				dir = _reflect(dir, pc.orient)
			else:                                  # prism recolours, passes straight
				col_name = pc.color
			seg_start = cell_center(nxt)
			cur = nxt
			continue
		var ti := _target_index(nxt)
		if ti >= 0:
			if targets[ti].color == col_name:
				targets[ti].lit = true
			cur = nxt                              # crystals are transparent
			continue
		if nxt == emitter_cell:
			beam_segments.append({"a": seg_start, "b": cell_center(nxt), "c": COLORS[col_name]})
			return
		cur = nxt
	beam_segments.append({"a": seg_start, "b": cell_center(cur), "c": COLORS[col_name]})


func _all_lit() -> bool:
	if targets.is_empty():
		return false
	for t in targets:
		if not t.lit:
			return false
	return true


# =============================================================================
#  Main loop
# =============================================================================
func _process(delta: float) -> void:
	if phase == Phase.PLAY:
		elapsed += delta
		_update_hover()
		_trace()
		_update_targets_visual()
		_update_lit_label()
		if _all_lit():
			_level_cleared()
	beam_node.queue_redraw()


func _update_lit_label() -> void:
	if lbl_lit == null:
		return
	var lit := 0
	for t in targets:
		if t.lit:
			lit += 1
	lbl_lit.text = "CRYSTALS LIT  %d / %d" % [lit, targets.size()]


func _update_targets_visual() -> void:
	var pulse := 0.5 + 0.5 * sin(Time.get_ticks_msec() / 240.0)
	for t in targets:
		var col: Color = COLORS[t.color]
		if t.lit:
			t.gem.modulate = col.lightened(0.25)
			t.glow.modulate = Color(col.r, col.g, col.b, 0.55 + pulse * 0.35)
			t.glow.scale = Vector2(0.95 + pulse * 0.12, 0.95 + pulse * 0.12)
			if not t._was:
				_on_target_lit(t)
		else:
			t.gem.modulate = col.darkened(0.62)
			t.glow.modulate = Color(col.r, col.g, col.b, 0.0)
		t._was = t.lit


func _on_target_lit(t: Dictionary) -> void:
	var pos: Vector2 = cell_center(t.cell)
	t.gem.scale = Vector2(CELL / 26.0 * 0.95, CELL / 26.0 * 0.95)
	t.gem.create_tween().tween_property(t.gem, "scale",
		Vector2(CELL / 26.0 * 0.62, CELL / 26.0 * 0.62), 0.34).set_trans(Tween.TRANS_BACK).set_ease(Tween.EASE_OUT)
	for i in range(12):
		_spark(pos + Vector2(randf_range(-12, 12), randf_range(-12, 12)), COLORS[t.color], true)


# =============================================================================
#  Player interaction
# =============================================================================
func _cell_at(p: Vector2) -> Vector2i:
	return Vector2i(int(floor((p.x - BOARD.position.x) / CELL)),
					int(floor((p.y - BOARD.position.y) / CELL)))


func _placeable(cell: Vector2i) -> bool:
	if not _in_grid(cell): return false
	if walls.has(cell): return false
	if cell == emitter_cell: return false
	if _target_index(cell) >= 0: return false
	return true


func _update_hover() -> void:
	var m := get_viewport().get_mouse_position()
	if not BOARD.has_point(m):
		has_hover = false
		return
	var cell := _cell_at(m)
	if not _in_grid(cell):
		has_hover = false
		return
	has_hover = true
	hover_cell = cell
	if pieces.has(cell):
		hover_kind = "edit"
	elif _placeable(cell):
		var stock := mirrors_left if tool == "mirror" else prisms_left
		hover_kind = "place" if stock > 0 else "nostock"
	else:
		hover_kind = "blocked"


func _unhandled_input(event: InputEvent) -> void:
	if event.is_action_pressed("ui_accept") and phase in [Phase.INTRO, Phase.INTERSTITIAL, Phase.VICTORY]:
		if _primary.is_valid():
			_primary.call()
		return
	if phase != Phase.PLAY:
		return
	if event is InputEventKey and event.pressed and not event.echo:
		match event.physical_keycode:
			KEY_M: _set_tool("mirror"); return
			KEY_P: _set_tool("prism"); return
			KEY_R: _reset_level(); return
	if event is InputEventMouseButton and event.pressed:
		var cell := _cell_at(event.position)
		if not _in_grid(cell):
			return
		if event.button_index == MOUSE_BUTTON_LEFT:
			_left_click(cell)
		elif event.button_index == MOUSE_BUTTON_RIGHT:
			_remove_piece(cell)


func _left_click(cell: Vector2i) -> void:
	if pieces.has(cell):
		var pc = pieces[cell]
		if pc.type == "mirror":
			pc.orient = "\\" if pc.orient == "/" else "/"
			pc.node.rotation = PI / 2 if pc.orient == "\\" else 0.0
			_pop(pc.node, CELL / 32.0)
		else:
			var i := prism_palette.find(pc.color)
			pc.color = prism_palette[(i + 1) % prism_palette.size()]
			pc.node.modulate = COLORS[pc.color]
			if pc.glow: pc.glow.modulate = Color(COLORS[pc.color].r, COLORS[pc.color].g, COLORS[pc.color].b, 0.5)
			_spark(cell_center(cell), COLORS[pc.color], true)
		return
	if not _placeable(cell):
		return
	if tool == "mirror" and mirrors_left > 0:
		_place_mirror(cell, "/")
		mirrors_left -= 1
	elif tool == "prism" and prisms_left > 0:
		_place_prism(cell, prism_palette[0])
		prisms_left -= 1
	_refresh_toolbar()


func _place_mirror(cell: Vector2i, orient: String) -> void:
	var node := _new_sprite("mirror", cell_center(cell), optics_root, 12, CELL / 32.0 * 0.9)
	node.rotation = PI / 2 if orient == "\\" else 0.0
	pieces[cell] = {"type": "mirror", "orient": orient, "color": "", "node": node, "glow": null}
	_pop(node, CELL / 32.0 * 0.9)
	_spark(cell_center(cell), Color("d4ecff"), true)


func _place_prism(cell: Vector2i, col: String) -> void:
	var pos := cell_center(cell)
	var glow := _new_sprite("glow", pos, optics_root, 11, 0.6)
	glow.modulate = Color(COLORS[col].r, COLORS[col].g, COLORS[col].b, 0.5)
	var node := _new_sprite("prism", pos, optics_root, 12, CELL / 30.0 * 0.92)
	node.modulate = COLORS[col]
	pieces[cell] = {"type": "prism", "orient": "", "color": col, "node": node, "glow": glow}
	_pop(node, CELL / 30.0 * 0.92)
	_spark(pos, COLORS[col], true)


func _remove_piece(cell: Vector2i) -> void:
	if not pieces.has(cell):
		return
	var pc = pieces[cell]
	if pc.node: pc.node.queue_free()
	if pc.glow: pc.glow.queue_free()
	if pc.type == "mirror":
		mirrors_left += 1
	else:
		prisms_left += 1
	pieces.erase(cell)
	_refresh_toolbar()


func _reset_level() -> void:
	for cell in pieces.keys():
		var pc = pieces[cell]
		if pc.node: pc.node.queue_free()
		if pc.glow: pc.glow.queue_free()
	pieces.clear()
	var cfg = CHAMBERS[level_index]
	mirrors_left = cfg.mirrors
	prisms_left = cfg.prisms
	_refresh_toolbar()
	_flash_toast("RESET", 0.6, Color("cfe6f5"))


func _set_tool(t: String) -> void:
	tool = t
	_refresh_toolbar()


# Places the current chamber's authored solution. Used by the verify harness
# (tools/laser_shot) as a built-in solvability self-test; not used in play.
func debug_solution_size() -> int:
	return CHAMBERS[level_index].solution.size()


func debug_place_piece(i: int) -> void:
	var s = CHAMBERS[level_index].solution[i]
	if s.t == "mirror":
		if mirrors_left > 0:
			_place_mirror(s.cell, s.o)
			mirrors_left -= 1
	else:
		if prisms_left > 0:
			_place_prism(s.cell, s.color)
			prisms_left -= 1
	_refresh_toolbar()


func debug_apply_solution() -> void:
	for i in range(debug_solution_size()):
		debug_place_piece(i)


# =============================================================================
#  Win flow
# =============================================================================
func _level_cleared() -> void:
	pieces_used_total += pieces.size()
	phase = Phase.INTERSTITIAL
	# celebratory beam flash already on; small delay then panel
	var grade := "CHAMBER CLEARED"
	if level_index >= CHAMBERS.size() - 1:
		_victory()
		return
	var nxt = CHAMBERS[level_index + 1]
	_show_panel(grade,
		"Every crystal sings with light.\n\nUp next: \"%s\".\n%s" % [nxt.name, nxt.hint],
		[{"text": "NEXT CHAMBER", "color": Color("2f9e5a"), "action": _next_level}],
		-1, COLORS[emitter_color])


func _next_level() -> void:
	_clear_overlay()
	_primary = Callable()
	_start_level(level_index + 1)


func _star_rating() -> int:
	var extra := pieces_used_total - par_total
	if extra <= 0: return 5
	elif extra <= 2: return 4
	elif extra <= 4: return 3
	elif extra <= 6: return 2
	return 1


func _victory() -> void:
	phase = Phase.VICTORY
	var stars := _star_rating()
	if record_on_win:
		_record(stars)
	var grade := "MASTER OF LIGHT" if stars >= 5 else ("FLAWLESS OPTICS" if stars >= 4 else "ARRAY ALIGNED")
	_show_panel(grade,
		"Every chamber is ablaze. Ashley's lab hums in perfect colour.\n\nPieces used  %d        Par  %d" % [pieces_used_total, par_total],
		[{"text": "CONTINUE", "color": Color("2f9e5a"), "action": _leave},
		 {"text": "RETRY", "color": Color("3a78a8"), "action": _retry}],
		stars, Color("f6e08a"))


func _retry() -> void:
	_clear_overlay()
	_primary = Callable()
	_start_run()


func _leave() -> void:
	if return_scene != "" and ResourceLoader.exists(return_scene):
		var sm = get_node_or_null("/root/SceneManager")
		if sm and sm.has_method("change_scene"):
			sm.change_scene(return_scene)
		else:
			get_tree().change_scene_to_file(return_scene)
	else:
		get_tree().reload_current_scene()


func _record(stars: int) -> void:
	var sm = get_node_or_null("/root/StarManager")
	if sm and sm.has_method("record_quest_stars"):
		var best := stars
		if sm.has_method("get_quest_stars"):
			best = max(stars, sm.get_quest_stars(quest_id))
		sm.record_quest_stars(quest_id, domain, best, 5)
	var em = get_node_or_null("/root/EndingManager")
	if em and em.has_method("complete_quest"):
		em.complete_quest(quest_id, domain, stars)


# =============================================================================
#  HUD
# =============================================================================
func _build_hud() -> void:
	hud = CanvasLayer.new()
	hud.layer = 5
	add_child(hud)
	var root := Control.new()
	root.set_anchors_preset(Control.PRESET_FULL_RECT)
	root.mouse_filter = Control.MOUSE_FILTER_IGNORE
	root.theme = _theme
	hud.add_child(root)

	# top banner (left)
	var banner := _panel("frame_banner", 8)
	banner.position = Vector2(28, 14)
	banner.custom_minimum_size = Vector2(352, 0)
	root.add_child(banner)
	var tvb := VBoxContainer.new()
	tvb.add_theme_constant_override("separation", -2)
	banner.add_child(tvb)
	var title := _label("◈  PRISM  ARRAY", 26, Color("aef4ff"))
	title.add_theme_color_override("font_outline_color", Color("06121c"))
	title.add_theme_constant_override("outline_size", 5)
	tvb.add_child(title)
	tvb.add_child(_label("THE  ART  OF  LIGHT", 13, Color("e8c24a")))

	# chamber / objective (right)
	var opanel := _panel("frame_panel", 8)
	opanel.position = Vector2(804, 14)
	opanel.custom_minimum_size = Vector2(320, 0)
	root.add_child(opanel)
	var ovb := VBoxContainer.new()
	ovb.add_theme_constant_override("separation", 3)
	opanel.add_child(ovb)
	lbl_chamber = _label("CHAMBER  1 / 3", 18, Color("e9f4ff"))
	ovb.add_child(lbl_chamber)
	var lrow := HBoxContainer.new()
	lrow.add_theme_constant_override("separation", 6)
	ovb.add_child(lrow)
	lrow.add_child(_icon("icon_target", 20))
	lbl_lit = _label("CRYSTALS LIT  0 / 1", 18, Color("aef4ff"))
	lrow.add_child(lbl_lit)

	# bottom toolbar
	var tb := _panel("frame_panel", 10)
	tb.position = Vector2(76, 556)
	tb.custom_minimum_size = Vector2(1000, 0)
	root.add_child(tb)
	var tvbox := VBoxContainer.new()
	tvbox.add_theme_constant_override("separation", 6)
	tb.add_child(tvbox)

	var trow := HBoxContainer.new()
	trow.add_theme_constant_override("separation", 14)
	trow.alignment = BoxContainer.ALIGNMENT_CENTER
	tvbox.add_child(trow)
	btn_mirror = _tool_button("icon_mirror", "MIRROR", func(): _set_tool("mirror"))
	btn_prism = _tool_button("icon_prism", "PRISM", func(): _set_tool("prism"))
	trow.add_child(btn_mirror)
	trow.add_child(btn_prism)
	var sep := Control.new(); sep.custom_minimum_size = Vector2(28, 0)
	trow.add_child(sep)
	var reset := _button("RESET", Color("c87a2e"))
	reset.add_theme_font_size_override("font_size", 16)
	reset.pressed.connect(_reset_level)
	trow.add_child(reset)

	var hint := _label("L-CLICK  place / rotate     ·     R-CLICK  remove     ·     [M] mirror   [P] prism   [R] reset", 15, Color("9fb6cc"))
	hint.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
	tvbox.add_child(hint)

	# chamber-title toast — flashes in the empty header gap (never over the board)
	toast = _label("", 27, Color("ffffff"))
	toast.set_anchors_preset(Control.PRESET_TOP_LEFT)
	toast.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
	toast.vertical_alignment = VERTICAL_ALIGNMENT_CENTER
	toast.add_theme_color_override("font_outline_color", Color("06101a"))
	toast.add_theme_constant_override("outline_size", 6)
	toast.position = Vector2(392, 22)
	toast.size = Vector2(408, 52)
	toast.custom_minimum_size = Vector2(408, 52)
	toast.modulate.a = 0.0
	root.add_child(toast)


func _tool_button(icon_name: String, text: String, action: Callable) -> Button:
	var b := Button.new()
	b.icon = _tex.get(icon_name)
	b.text = "  " + text + "  ×0"
	b.focus_mode = Control.FOCUS_NONE
	b.add_theme_font_size_override("font_size", 17)
	b.add_theme_color_override("font_color", Color("dceaf6"))
	b.add_theme_constant_override("icon_max_width", 22)
	b.add_theme_stylebox_override("normal", _frame_box("slot_off", 12, 7))
	b.add_theme_stylebox_override("hover", _frame_box("slot_off", 12, 7))
	b.add_theme_stylebox_override("pressed", _frame_box("slot_on", 12, 7))
	b.pressed.connect(action)
	return b


func _refresh_toolbar() -> void:
	if btn_mirror:
		btn_mirror.text = "  MIRROR  ×%d" % mirrors_left
		btn_mirror.add_theme_stylebox_override("normal", _frame_box(("slot_on" if tool == "mirror" else "slot_off"), 12, 7))
		btn_mirror.add_theme_stylebox_override("hover", _frame_box(("slot_on" if tool == "mirror" else "slot_off"), 12, 7))
		btn_mirror.add_theme_color_override("font_color", Color("aef4ff") if tool == "mirror" else Color("8fa6bc"))
	if btn_prism:
		btn_prism.text = "  PRISM  ×%d" % prisms_left
		btn_prism.add_theme_stylebox_override("normal", _frame_box(("slot_on" if tool == "prism" else "slot_off"), 12, 7))
		btn_prism.add_theme_stylebox_override("hover", _frame_box(("slot_on" if tool == "prism" else "slot_off"), 12, 7))
		btn_prism.add_theme_color_override("font_color", Color("aef4ff") if tool == "prism" else Color("8fa6bc"))
		btn_prism.disabled = prisms_left <= 0 and not _has_placed_prism()
	if lbl_lit:
		var lit := 0
		for t in targets:
			if t.lit: lit += 1
		lbl_lit.text = "CRYSTALS LIT  %d / %d" % [lit, targets.size()]


func _has_placed_prism() -> bool:
	for c in pieces.keys():
		if pieces[c].type == "prism":
			return true
	return false


# =============================================================================
#  Overlay panels (intro / interstitial / victory)
# =============================================================================
func _build_overlay() -> void:
	overlay = CanvasLayer.new()
	overlay.layer = 12
	add_child(overlay)


func _clear_overlay() -> void:
	for c in overlay.get_children():
		c.queue_free()


func _show_intro() -> void:
	phase = Phase.INTRO
	_show_panel("PRISM  ARRAY",
		"Ashley jostled the future-lab's optics out of alignment — and only an artist of light can set them right.\n\nFire the laser through MIRRORS and PRISMS so every crystal blazes in its true colour. Three chambers await. Use as few pieces as you can: elegance earns stars.",
		[{"text": "ENTER THE LAB", "color": Color("2f9e5a"), "action": _start_run}],
		-1, Color("aef4ff"))


func _start_run() -> void:
	pieces_used_total = 0
	par_total = 0
	for ch in CHAMBERS:
		par_total += int(ch.par)
	elapsed = 0.0
	_clear_overlay()
	_primary = Callable()
	_start_level(0)


func _show_panel(title_text: String, body_text: String, buttons: Array,
		stars := -1, accent := Color("aef4ff")) -> void:
	_clear_overlay()
	var root := Control.new()
	root.set_anchors_preset(Control.PRESET_FULL_RECT)
	root.theme = _theme
	overlay.add_child(root)

	var dim := ColorRect.new()
	dim.color = Color(0.01, 0.02, 0.05, 0.66)
	dim.set_anchors_preset(Control.PRESET_FULL_RECT)
	root.add_child(dim)

	var center := CenterContainer.new()
	center.set_anchors_preset(Control.PRESET_FULL_RECT)
	center.mouse_filter = Control.MOUSE_FILTER_IGNORE
	root.add_child(center)
	var panel := _panel("frame_window", 26)
	panel.custom_minimum_size = Vector2(640, 0)
	center.add_child(panel)
	var vb := VBoxContainer.new()
	vb.add_theme_constant_override("separation", 14)
	vb.alignment = BoxContainer.ALIGNMENT_CENTER
	panel.add_child(vb)

	var t := _label(title_text, 34, accent)
	t.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
	t.add_theme_color_override("font_outline_color", Color("0a0814"))
	t.add_theme_constant_override("outline_size", 5)
	vb.add_child(t)

	if stars >= 0:
		var srow := HBoxContainer.new()
		srow.alignment = BoxContainer.ALIGNMENT_CENTER
		srow.add_theme_constant_override("separation", 8)
		vb.add_child(srow)
		for i in range(5):
			var s := TextureRect.new()
			s.texture = _tex.get("star_full") if i < stars else _tex.get("star_empty")
			s.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST
			s.custom_minimum_size = Vector2(46, 46)
			s.stretch_mode = TextureRect.STRETCH_KEEP_ASPECT_CENTERED
			srow.add_child(s)
			if i < stars:
				s.scale = Vector2.ZERO
				s.pivot_offset = Vector2(23, 23)
				var tw := s.create_tween().set_trans(Tween.TRANS_BACK).set_ease(Tween.EASE_OUT)
				tw.tween_interval(0.14 * i + 0.2)
				tw.tween_property(s, "scale", Vector2.ONE, 0.34)

	if body_text != "":
		var b := _label(body_text, 18, Color("d8e6f2"))
		b.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
		b.autowrap_mode = TextServer.AUTOWRAP_WORD_SMART
		b.custom_minimum_size = Vector2(580, 0)
		vb.add_child(b)

	var brow := HBoxContainer.new()
	brow.alignment = BoxContainer.ALIGNMENT_CENTER
	brow.add_theme_constant_override("separation", 16)
	vb.add_child(brow)
	for spec in buttons:
		var btn := _button(spec.text, spec.color)
		btn.pressed.connect(spec.action)
		brow.add_child(btn)
	if buttons.size() > 0:
		_primary = buttons[0].action

	panel.pivot_offset = panel.custom_minimum_size * 0.5
	panel.scale = Vector2(0.86, 0.86)
	panel.modulate.a = 0.0
	var tw2 := panel.create_tween().set_parallel(true)
	tw2.tween_property(panel, "scale", Vector2.ONE, 0.28).set_trans(Tween.TRANS_BACK).set_ease(Tween.EASE_OUT)
	tw2.tween_property(panel, "modulate:a", 1.0, 0.2)


# =============================================================================
#  FX + factories
# =============================================================================
func _spark(pos: Vector2, col: Color, burst := false) -> void:
	var s := Sprite2D.new()
	s.texture = _tex.get("spark")
	s.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST
	s.position = pos
	s.modulate = col
	fx_root.add_child(s)
	var tw := s.create_tween().set_parallel(true)
	var drift := Vector2(randf_range(-26, 26), randf_range(-26, 26)) if burst else Vector2(0, -14)
	tw.tween_property(s, "position", pos + drift, 0.42)
	tw.tween_property(s, "scale", Vector2(0.2, 0.2), 0.42)
	tw.tween_property(s, "modulate:a", 0.0, 0.42)
	tw.chain().tween_callback(s.queue_free)


func _pop(node: Node2D, target_scale: float) -> void:
	node.scale = Vector2(target_scale * 1.4, target_scale * 1.4)
	node.create_tween().tween_property(node, "scale", Vector2(target_scale, target_scale), 0.26).set_trans(Tween.TRANS_BACK).set_ease(Tween.EASE_OUT)


func _flash_toast(text: String, hold: float, col: Color = Color.WHITE) -> void:
	toast.text = text
	toast.add_theme_color_override("font_color", col)
	toast.modulate.a = 0.0
	if text == "":
		return
	var tw := toast.create_tween()
	tw.tween_property(toast, "modulate:a", 1.0, 0.18)
	tw.tween_interval(hold)
	tw.tween_property(toast, "modulate:a", 0.0, 0.4)


func _label(text: String, size: int, col: Color) -> Label:
	var l := Label.new()
	l.text = text
	l.add_theme_font_size_override("font_size", size)
	l.add_theme_color_override("font_color", col)
	return l


func _icon(tex_name: String, sz: int) -> TextureRect:
	var t := TextureRect.new()
	t.texture = _tex.get(tex_name)
	t.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST
	t.custom_minimum_size = Vector2(sz, sz)
	t.stretch_mode = TextureRect.STRETCH_KEEP_ASPECT_CENTERED
	t.size_flags_vertical = Control.SIZE_SHRINK_CENTER
	return t


func _panel(frame_name: String, margin: int) -> PanelContainer:
	var p := PanelContainer.new()
	p.add_theme_stylebox_override("panel", _frame_box(frame_name, margin))
	return p


func _frame_box(frame_name: String, content := 8, tmargin := 7) -> StyleBox:
	var tex: Texture2D = _tex.get(frame_name)
	if tex:
		var sb := StyleBoxTexture.new()
		sb.texture = tex
		sb.texture_margin_left = tmargin
		sb.texture_margin_top = tmargin
		sb.texture_margin_right = tmargin
		sb.texture_margin_bottom = tmargin
		sb.content_margin_left = content
		sb.content_margin_right = content
		sb.content_margin_top = content
		sb.content_margin_bottom = content
		return sb
	var f := StyleBoxFlat.new()
	f.bg_color = Color("141027")
	f.border_color = Color("2f7d99")
	f.set_border_width_all(2)
	return f


func _button(text: String, col: Color) -> Button:
	var b := Button.new()
	b.text = text
	b.focus_mode = Control.FOCUS_NONE
	b.add_theme_stylebox_override("normal", _button_box(col))
	b.add_theme_stylebox_override("hover", _button_box(col.lightened(0.16)))
	b.add_theme_stylebox_override("pressed", _button_box(col.darkened(0.2)))
	b.add_theme_stylebox_override("disabled", _button_box(col.darkened(0.5)))
	b.add_theme_color_override("font_color", Color("f7fffb"))
	b.add_theme_color_override("font_hover_color", Color("ffffff"))
	b.add_theme_color_override("font_disabled_color", Color("8090a0"))
	b.add_theme_font_size_override("font_size", 20)
	return b


func _button_box(col: Color) -> StyleBox:
	var tex: Texture2D = _tex.get("button")
	if tex:
		var sb := StyleBoxTexture.new()
		sb.texture = tex
		sb.modulate_color = col
		sb.texture_margin_left = 5
		sb.texture_margin_top = 5
		sb.texture_margin_right = 5
		sb.texture_margin_bottom = 5
		sb.content_margin_left = 22
		sb.content_margin_right = 22
		sb.content_margin_top = 10
		sb.content_margin_bottom = 10
		return sb
	var f := StyleBoxFlat.new()
	f.bg_color = col.darkened(0.15)
	f.border_color = col.lightened(0.25)
	f.set_border_width_all(2)
	return f


# =============================================================================
#  Beam + hover renderer
# =============================================================================
class _Beam extends Node2D:
	var quest

	func _draw() -> void:
		if quest == null:
			return
		var t := Time.get_ticks_msec() / 1000.0
		var flick := 0.86 + 0.14 * sin(t * 9.0)
		for seg in quest.beam_segments:
			var a: Vector2 = seg.a
			var b: Vector2 = seg.b
			var col: Color = seg.c
			# outer glow
			draw_line(a, b, Color(col.r, col.g, col.b, 0.16 * flick), 18.0, true)
			draw_line(a, b, Color(col.r, col.g, col.b, 0.30 * flick), 10.0, true)
			# body
			draw_line(a, b, Color(col.r, col.g, col.b, 0.9), 5.0, true)
			# hot white core
			var core := col.lerp(Color.WHITE, 0.7)
			draw_line(a, b, Color(core.r, core.g, core.b, 0.95), 2.0, true)
			# bend knot
			draw_circle(b, 5.0, Color(col.r, col.g, col.b, 0.5))
			draw_circle(b, 2.4, Color(core.r, core.g, core.b, 0.9))
		# hover highlight
		if quest.has_hover and quest.phase == quest.Phase.PLAY:
			var c: Vector2 = quest.cell_center(quest.hover_cell)
			var r := Rect2(c - Vector2(30, 30), Vector2(60, 60))
			var hc := Color(0.6, 0.95, 1.0)
			match quest.hover_kind:
				"place": hc = Color(0.45, 1.0, 0.6)
				"edit": hc = Color(0.6, 0.92, 1.0)
				"nostock": hc = Color(1.0, 0.7, 0.3)
				"blocked": hc = Color(1.0, 0.4, 0.45)
			draw_rect(r, Color(hc.r, hc.g, hc.b, 0.12), true)
			draw_rect(r, Color(hc.r, hc.g, hc.b, 0.85), false, 2.0)
			# little corner ticks
			for corner in [r.position, Vector2(r.end.x, r.position.y), Vector2(r.position.x, r.end.y), r.end]:
				draw_circle(corner, 2.2, Color(hc.r, hc.g, hc.b, 0.9))
