extends Node2D
# =============================================================================
#  NANOBOT SURGEON  —  self-contained pixel-art action quest
# =============================================================================
# Pilot a surgical nanobot through a patient's bloodstream and seal every
# tissue breach while dodging the pathogens, microbes and clots drifting
# through the vessel.  Three patients of rising difficulty; a single shared
# "patient stability" meter; speed + stability decide a 0–5 star score.
#
# Built in the same house style as the IMMUNE DEFENSE / XENO LAB remasters:
#   * all art generated by tools/make_nanobot.py -> assets/generated/nanobot/
#   * the determination pixel font on every label/button
#   * beveled 9-slice StyleBoxTexture panels & buttons, animated star sprites
#
# Wiring: launched from the hospital ward (scenes/world_3.tscn); records stars
# as medicine_quest_3 / "Medicine"; returns to the ward when finished.
# =============================================================================

const ART := "res://assets/generated/nanobot/"
const FONT_PATH := "res://art/Dialogue/determination.ttf"

@export var return_scene: String = "res://scenes/world_3.tscn"
@export var quest_id: String = "medicine_quest_3"
@export var domain: String = "Medicine"
var record_on_win := true                       # harness sets false

# ---- tuning -----------------------------------------------------------------
const FIELD := Rect2(48, 100, 1056, 496)        # play area (matches 1152x648)
const BOT_RADIUS := 12.0
const SITE_RADIUS := 24.0
const MAX_SPEED := 250.0
const ACCEL := 1100.0
const DRAG := 4.2
const KNOCKBACK := 360.0
const HIT_IFRAMES := 0.9
const HEAL_REWARD := 7.0                         # stability regained per seal

# patient -> {sites, hazards:[types], speed, repair_time}
const PATIENTS := [
	{"name": "PATIENT 01  ·  Mara Voss", "cond": "Arterial micro-tears",
	 "sites": 3, "hazards": ["pathogen", "microbe"], "speed": 70.0, "repair": 1.4},
	{"name": "PATIENT 02  ·  Eli Tan", "cond": "Septic infiltration",
	 "sites": 4, "hazards": ["pathogen", "microbe", "clot"], "speed": 95.0, "repair": 1.6},
	{"name": "PATIENT 03  ·  Dr. Okafor", "cond": "Critical clot cascade",
	 "sites": 5, "hazards": ["pathogen", "microbe", "clot", "pathogen"], "speed": 122.0, "repair": 1.8},
]

enum Phase { INTRO, PLAY, INTERSTITIAL, VICTORY, FAIL }

# ---- state ------------------------------------------------------------------
var _tex := {}
var phase: int = Phase.INTRO
var patient_index := 0
var stability := 100.0
var score := 0
var elapsed := 0.0
var sites := []          # [{node, glow, pos, progress, healed}]
var hazards := []        # [{node, pos, vel, radius}]
var decor := []          # drifting rbc sprites [{node,vel}]
var bot_vel := Vector2.ZERO
var bot_angle := -PI / 2
var iframe := 0.0
var shake := 0.0
var _primary: Callable = Callable()

# ---- nodes ------------------------------------------------------------------
var play_root: Node2D
var gauge: Node2D
var bot: Sprite2D
var bot_glow: Sprite2D
var hud: CanvasLayer
var overlay: CanvasLayer
var bg_layer: CanvasLayer
var flash: ColorRect
var toast: Label
var lbl_seal: Label
var lbl_patient: Label
var bar_fill: ColorRect
var _theme: Theme


# =============================================================================
func _ready() -> void:
	randomize()
	_load_textures()
	_theme = Theme.new()
	if ResourceLoader.exists(FONT_PATH):
		_theme.default_font = load(FONT_PATH)
	_theme.default_font_size = 18

	_build_background()
	play_root = Node2D.new()
	add_child(play_root)
	gauge = _Gauge.new()
	gauge.quest = self
	gauge.z_index = 50
	play_root.add_child(gauge)
	_build_bot()
	_build_hud()
	_build_overlay()
	_show_intro()


func _load_textures() -> void:
	for n in ["bg", "frame_panel", "frame_window", "frame_banner", "button",
			"bar_bg", "bar_fill", "nanobot", "breach", "healed", "pathogen",
			"microbe", "clot", "rbc", "spark", "glow", "icon_integrity",
			"icon_repair", "icon_clock", "star_full", "star_empty"]:
		var p: String = ART + n + ".png"
		_tex[n] = load(p) if ResourceLoader.exists(p) else null


# ---- construction -----------------------------------------------------------
func _build_background() -> void:
	bg_layer = CanvasLayer.new()
	bg_layer.layer = -10
	add_child(bg_layer)
	var tr := TextureRect.new()
	tr.texture = _tex.get("bg")
	tr.set_anchors_preset(Control.PRESET_FULL_RECT)
	tr.expand_mode = TextureRect.EXPAND_IGNORE_SIZE
	tr.stretch_mode = TextureRect.STRETCH_KEEP_ASPECT_COVERED
	tr.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST
	bg_layer.add_child(tr)


func _build_bot() -> void:
	bot_glow = Sprite2D.new()
	bot_glow.texture = _tex.get("glow")
	bot_glow.modulate = Color(0.5, 1.0, 0.95, 0.7)
	bot_glow.scale = Vector2(0.85, 0.85)
	bot_glow.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST
	play_root.add_child(bot_glow)

	bot = Sprite2D.new()
	bot.texture = _tex.get("nanobot")
	bot.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST
	bot.z_index = 20
	play_root.add_child(bot)
	bot.position = FIELD.position + FIELD.size * 0.5
	bot_glow.position = bot.position


func _sprite(tex_name: String, pos: Vector2, z := 0) -> Sprite2D:
	var s := Sprite2D.new()
	s.texture = _tex.get(tex_name)
	s.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST
	s.position = pos
	s.z_index = z
	play_root.add_child(s)
	return s


# =============================================================================
#  HUD
# =============================================================================
func _build_hud() -> void:
	hud = CanvasLayer.new()
	hud.layer = 5
	add_child(hud)
	var root := Control.new()
	root.set_anchors_preset(Control.PRESET_FULL_RECT)
	root.mouse_filter = Control.MOUSE_FILTER_IGNORE
	root.theme = _theme
	hud.add_child(root)

	# top banner (title, left)
	var banner := _panel("frame_banner", 8)
	banner.position = Vector2(28, 22)
	banner.custom_minimum_size = Vector2(360, 0)
	root.add_child(banner)
	var tvb := VBoxContainer.new()
	tvb.add_theme_constant_override("separation", -2)
	banner.add_child(tvb)
	var title := _label("⬡  NANOBOT  SURGEON", 26, Color("ffe08a"))
	title.add_theme_color_override("font_outline_color", Color("1a0c04"))
	title.add_theme_constant_override("outline_size", 5)
	tvb.add_child(title)
	tvb.add_child(_label("MICROSURGICAL OPERATION", 13, Color("d18a98")))

	# patient pill (top-right)
	var ppanel := _panel("frame_panel", 8)
	ppanel.position = Vector2(842, 22)
	ppanel.custom_minimum_size = Vector2(282, 0)
	root.add_child(ppanel)
	var pvb := VBoxContainer.new()
	pvb.add_theme_constant_override("separation", 2)
	ppanel.add_child(pvb)
	lbl_patient = _label("PATIENT 1 / 3", 18, Color("ffd0d8"))
	pvb.add_child(lbl_patient)
	# integrity row
	var irow := HBoxContainer.new()
	irow.add_theme_constant_override("separation", 6)
	pvb.add_child(irow)
	irow.add_child(_icon("icon_integrity", 20))
	var bar := _make_bar(196)
	irow.add_child(bar)

	# objective (under banner)
	var obj := _panel("frame_panel", 8)
	obj.position = Vector2(28, 92)
	root.add_child(obj)
	var orow := HBoxContainer.new()
	orow.add_theme_constant_override("separation", 8)
	obj.add_child(orow)
	orow.add_child(_icon("icon_repair", 20))
	lbl_seal = _label("BREACHES SEALED  0 / 3", 18, Color("8ff6ec"))
	orow.add_child(lbl_seal)

	# controls strip (bottom)
	var strip := _panel("frame_panel", 6)
	strip.position = Vector2(28, 604)
	strip.custom_minimum_size = Vector2(1096, 0)
	root.add_child(strip)
	var clbl := _label("ARROWS / WASD  —  pilot the nanobot       ·       glide onto a red breach to seal it       ·       avoid pathogens & clots", 15, Color("e7c2cc"))
	clbl.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
	strip.add_child(clbl)

	# center toast
	toast = _label("", 40, Color("ffffff"))
	toast.set_anchors_preset(Control.PRESET_CENTER)
	toast.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
	toast.add_theme_color_override("font_outline_color", Color("10060a"))
	toast.add_theme_constant_override("outline_size", 6)
	toast.position = Vector2(-380, -40)
	toast.custom_minimum_size = Vector2(760, 0)
	toast.modulate.a = 0.0
	root.add_child(toast)

	# damage flash
	flash = ColorRect.new()
	flash.color = Color(0.85, 0.1, 0.18, 0.0)
	flash.set_anchors_preset(Control.PRESET_FULL_RECT)
	flash.mouse_filter = Control.MOUSE_FILTER_IGNORE
	root.add_child(flash)


func _make_bar(width: int) -> Control:
	var holder := Control.new()
	holder.custom_minimum_size = Vector2(width, 22)
	var track := TextureRect.new()
	track.texture = _tex.get("bar_bg")
	track.set_anchors_preset(Control.PRESET_FULL_RECT)
	track.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST
	track.stretch_mode = TextureRect.STRETCH_SCALE
	holder.add_child(track)
	bar_fill = ColorRect.new()
	bar_fill.color = Color("4fd17a")
	bar_fill.position = Vector2(3, 3)
	bar_fill.size = Vector2(width - 6, 16)
	holder.add_child(bar_fill)
	holder.set_meta("w", width - 6)
	return holder


# =============================================================================
#  Overlay panels (intro / interstitial / victory / fail)
# =============================================================================
func _build_overlay() -> void:
	overlay = CanvasLayer.new()
	overlay.layer = 10
	add_child(overlay)


func _clear_overlay() -> void:
	for c in overlay.get_children():
		c.queue_free()


func _show_panel(title_text: String, body_text: String, buttons: Array,
		stars := -1, accent := Color("ffe08a")) -> void:
	_clear_overlay()
	var root := Control.new()
	root.set_anchors_preset(Control.PRESET_FULL_RECT)
	root.theme = _theme
	overlay.add_child(root)

	var dim := ColorRect.new()
	dim.color = Color(0.02, 0.0, 0.02, 0.62)
	dim.set_anchors_preset(Control.PRESET_FULL_RECT)
	root.add_child(dim)

	var center := CenterContainer.new()
	center.set_anchors_preset(Control.PRESET_FULL_RECT)
	center.mouse_filter = Control.MOUSE_FILTER_IGNORE
	root.add_child(center)
	var panel := _panel("frame_window", 26)
	panel.custom_minimum_size = Vector2(620, 0)
	center.add_child(panel)
	var vb := VBoxContainer.new()
	vb.add_theme_constant_override("separation", 14)
	vb.alignment = BoxContainer.ALIGNMENT_CENTER
	panel.add_child(vb)

	var t := _label(title_text, 34, accent)
	t.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
	t.add_theme_color_override("font_outline_color", Color("16080c"))
	t.add_theme_constant_override("outline_size", 5)
	vb.add_child(t)

	if stars >= 0:
		var srow := HBoxContainer.new()
		srow.alignment = BoxContainer.ALIGNMENT_CENTER
		srow.add_theme_constant_override("separation", 8)
		vb.add_child(srow)
		for i in range(5):
			var s := TextureRect.new()
			s.texture = _tex.get("star_full") if i < stars else _tex.get("star_empty")
			s.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST
			s.custom_minimum_size = Vector2(46, 46)
			s.stretch_mode = TextureRect.STRETCH_KEEP_ASPECT_CENTERED
			srow.add_child(s)
			if i < stars:
				s.scale = Vector2.ZERO
				s.pivot_offset = Vector2(23, 23)
				var tw := s.create_tween().set_trans(Tween.TRANS_BACK).set_ease(Tween.EASE_OUT)
				tw.tween_interval(0.14 * i + 0.2)
				tw.tween_property(s, "scale", Vector2.ONE, 0.34)

	if body_text != "":
		var b := _label(body_text, 18, Color("e7d4c0"))
		b.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
		b.autowrap_mode = TextServer.AUTOWRAP_WORD_SMART
		b.custom_minimum_size = Vector2(560, 0)
		vb.add_child(b)

	var brow := HBoxContainer.new()
	brow.alignment = BoxContainer.ALIGNMENT_CENTER
	brow.add_theme_constant_override("separation", 16)
	vb.add_child(brow)
	for spec in buttons:
		var btn := _button(spec.text, spec.color)
		btn.pressed.connect(spec.action)
		brow.add_child(btn)
	if buttons.size() > 0:
		_primary = buttons[0].action

	# pop the panel in
	panel.pivot_offset = panel.custom_minimum_size * 0.5
	panel.scale = Vector2(0.85, 0.85)
	panel.modulate.a = 0.0
	var tw2 := panel.create_tween().set_parallel(true)
	tw2.tween_property(panel, "scale", Vector2.ONE, 0.28).set_trans(Tween.TRANS_BACK).set_ease(Tween.EASE_OUT)
	tw2.tween_property(panel, "modulate:a", 1.0, 0.2)


func _show_intro() -> void:
	phase = Phase.INTRO
	_show_panel(
		"NANOBOT  SURGEON",
		"You are piloting an experimental surgical nanobot through three critical patients.\n\nGuide it onto every glowing red breach to seal the tissue — but the bloodstream is swarming with pathogens and clots. Every collision destabilises the patient.\n\nKeep them stable. Work fast. Save all three.",
		[{"text": "BEGIN OPERATION", "color": Color("2f9e5a"), "action": _start_run}],
		-1, Color("ffe08a"))


func _start_run() -> void:
	score = 0
	stability = 100.0
	elapsed = 0.0
	patient_index = 0
	_clear_overlay()
	_primary = Callable()
	_start_patient(0)


# =============================================================================
#  Patient setup
# =============================================================================
func _clear_gameplay() -> void:
	for s in sites:
		s.node.queue_free()
		if s.glow:
			s.glow.queue_free()
	for h in hazards:
		h.node.queue_free()
	for d in decor:
		d.node.queue_free()
	sites.clear(); hazards.clear(); decor.clear()


func _start_patient(idx: int) -> void:
	patient_index = idx
	var cfg = PATIENTS[idx]
	_clear_gameplay()
	elapsed = 0.0
	bot.position = FIELD.position + FIELD.size * 0.5
	bot_vel = Vector2.ZERO
	iframe = 0.0

	# scatter breaches, spaced out and away from the spawn
	var placed := []
	var tries := 0
	while placed.size() < int(cfg.sites) and tries < 400:
		tries += 1
		var p := Vector2(randf_range(FIELD.position.x + 70, FIELD.end.x - 70),
						 randf_range(FIELD.position.y + 70, FIELD.end.y - 70))
		if p.distance_to(bot.position) < 150:
			continue
		var ok := true
		for q in placed:
			if p.distance_to(q) < 150:
				ok = false; break
		if ok:
			placed.append(p)
	for p in placed:
		var gl := _sprite("glow", p, 1)
		gl.modulate = Color(1.0, 0.3, 0.34, 0.6)
		gl.scale = Vector2(0.7, 0.7)
		var node := _sprite("breach", p, 5)
		sites.append({"node": node, "glow": gl, "pos": p, "progress": 0.0, "healed": false})

	# hazards
	for htype in cfg.hazards:
		var hp := Vector2(randf_range(FIELD.position.x + 40, FIELD.end.x - 40),
						  randf_range(FIELD.position.y + 40, FIELD.end.y - 40))
		while hp.distance_to(bot.position) < 160:
			hp = Vector2(randf_range(FIELD.position.x + 40, FIELD.end.x - 40),
						 randf_range(FIELD.position.y + 40, FIELD.end.y - 40))
		var ang := randf() * TAU
		var rad := 13.0
		if htype == "clot":
			rad = 16.0
		var node := _sprite(htype, hp, 8)
		hazards.append({"node": node, "pos": hp, "type": htype,
			"vel": Vector2(cos(ang), sin(ang)) * float(cfg.speed), "radius": rad})

	# ambient red-blood-cell decor
	for i in range(10):
		var dp := Vector2(randf_range(FIELD.position.x, FIELD.end.x),
						  randf_range(FIELD.position.y, FIELD.end.y))
		var node := _sprite("rbc", dp, 0)
		node.modulate.a = 0.5
		node.scale = Vector2(0.9, 0.9)
		decor.append({"node": node, "vel": Vector2(randf_range(-18, 18), randf_range(-18, 18))})

	lbl_patient.text = "PATIENT %d / 3" % (idx + 1)
	_update_seal_label()
	_flash_toast(cfg.name, 1.6, Color("ffd0d8"))
	phase = Phase.PLAY


func _update_seal_label() -> void:
	var done := 0
	for s in sites:
		if s.healed:
			done += 1
	lbl_seal.text = "BREACHES SEALED  %d / %d" % [done, sites.size()]


# =============================================================================
#  Main loop
# =============================================================================
func _process(delta: float) -> void:
	# shake decay applies in any phase
	if shake > 0.0:
		shake = max(0.0, shake - delta * 36.0)
		play_root.position = Vector2(randf_range(-shake, shake), randf_range(-shake, shake))
	else:
		play_root.position = Vector2.ZERO
	if flash.color.a > 0.0:
		flash.color.a = max(0.0, flash.color.a - delta * 2.2)

	if phase != Phase.PLAY:
		_drift_decor(delta)
		return

	elapsed += delta
	iframe = max(0.0, iframe - delta)
	_pilot(delta)
	_repair(delta)
	_move_hazards(delta)
	_drift_decor(delta)
	_update_bar()
	gauge.queue_redraw()


func _pilot(delta: float) -> void:
	var dir := Input.get_vector("ui_left", "ui_right", "ui_up", "ui_down")
	var k := Vector2.ZERO
	if Input.is_physical_key_pressed(KEY_A): k.x -= 1
	if Input.is_physical_key_pressed(KEY_D): k.x += 1
	if Input.is_physical_key_pressed(KEY_W): k.y -= 1
	if Input.is_physical_key_pressed(KEY_S): k.y += 1
	if k != Vector2.ZERO:
		dir = k.normalized()
	if dir != Vector2.ZERO:
		bot_vel += dir * ACCEL * delta
		bot_angle = dir.angle()
	bot_vel = bot_vel.lerp(Vector2.ZERO, clamp(DRAG * delta, 0.0, 1.0))
	if bot_vel.length() > MAX_SPEED:
		bot_vel = bot_vel.normalized() * MAX_SPEED
	bot.position += bot_vel * delta
	bot.position.x = clamp(bot.position.x, FIELD.position.x + BOT_RADIUS, FIELD.end.x - BOT_RADIUS)
	bot.position.y = clamp(bot.position.y, FIELD.position.y + BOT_RADIUS, FIELD.end.y - BOT_RADIUS)
	bot.rotation = bot_angle + PI / 2          # art points up
	bot_glow.position = bot.position
	var sp := bot_vel.length() / MAX_SPEED
	bot_glow.scale = Vector2(0.8 + sp * 0.4, 0.8 + sp * 0.4)


func _repair(delta: float) -> void:
	var cfg = PATIENTS[patient_index]
	for s in sites:
		if s.healed:
			continue
		if bot.position.distance_to(s.pos) < SITE_RADIUS + BOT_RADIUS:
			s.progress += delta / float(cfg.repair)
			if randf() < 0.30:
				_spark(s.pos + Vector2(randf_range(-14, 14), randf_range(-14, 14)), Color("8ff6ec"))
			if s.progress >= 1.0:
				_seal(s)
		else:
			s.progress = max(0.0, s.progress - delta * 0.5)   # slowly decays if you leave


func _seal(s: Dictionary) -> void:
	s.healed = true
	s.progress = 1.0
	s.node.texture = _tex.get("healed")
	if s.glow:
		s.glow.modulate = Color(0.4, 1.0, 0.9, 0.6)
	# pop
	s.node.scale = Vector2(1.35, 1.35)
	s.node.create_tween().tween_property(s.node, "scale", Vector2.ONE, 0.3).set_trans(Tween.TRANS_BACK).set_ease(Tween.EASE_OUT)
	for i in range(14):
		_spark(s.pos + Vector2(randf_range(-8, 8), randf_range(-8, 8)), Color("8ff6ec"), true)
	stability = min(100.0, stability + HEAL_REWARD)
	score += 150
	_update_seal_label()
	_flash_toast("BREACH SEALED", 0.8, Color("8ff6ec"))
	# all done?
	for site in sites:
		if not site.healed:
			return
	_patient_cleared()


func _patient_cleared() -> void:
	score += int(stability) + max(0, 240 - int(elapsed * 8))
	if patient_index >= PATIENTS.size() - 1:
		_victory()
	else:
		phase = Phase.INTERSTITIAL
		var nxt = PATIENTS[patient_index + 1]
		_show_panel(
			"PATIENT STABILISED",
			"Tissue integrity restored. The patient is out of danger.\n\nNext: %s — %s.\nStability carries over: %d%%." % [nxt.name, nxt.cond, int(stability)],
			[{"text": "PROCEED", "color": Color("2f9e5a"), "action": _next_patient}],
			-1, Color("8ff6ec"))


func _next_patient() -> void:
	_clear_overlay()
	_primary = Callable()
	_start_patient(patient_index + 1)


func _move_hazards(delta: float) -> void:
	for h in hazards:
		h.pos += h.vel * delta
		if h.pos.x < FIELD.position.x + h.radius:
			h.pos.x = FIELD.position.x + h.radius; h.vel.x = abs(h.vel.x)
		elif h.pos.x > FIELD.end.x - h.radius:
			h.pos.x = FIELD.end.x - h.radius; h.vel.x = -abs(h.vel.x)
		if h.pos.y < FIELD.position.y + h.radius:
			h.pos.y = FIELD.position.y + h.radius; h.vel.y = abs(h.vel.y)
		elif h.pos.y > FIELD.end.y - h.radius:
			h.pos.y = FIELD.end.y - h.radius; h.vel.y = -abs(h.vel.y)
		h.node.position = h.pos
		h.node.rotation += delta * (1.2 if h.type == "pathogen" else 0.4)
		if iframe <= 0.0 and bot.position.distance_to(h.pos) < h.radius + BOT_RADIUS:
			_hit(h)


func _hit(h: Dictionary) -> void:
	var dmg := 14.0
	if h.type == "clot":
		dmg = 20.0
	stability = max(0.0, stability - dmg)
	iframe = HIT_IFRAMES
	bot_vel = (bot.position - h.pos).normalized() * KNOCKBACK
	shake = 7.0
	flash.color.a = 0.5
	for i in range(8):
		_spark(bot.position + Vector2(randf_range(-10, 10), randf_range(-10, 10)), Color("ff6a78"), true)
	# damage blink
	var tw := bot.create_tween()
	tw.tween_property(bot, "modulate", Color(1, 0.5, 0.5, 1), 0.08)
	tw.tween_property(bot, "modulate", Color(1, 1, 1, 1), 0.2)
	if stability <= 0.0:
		_fail()


func _drift_decor(delta: float) -> void:
	for d in decor:
		var n: Sprite2D = d.node
		n.position += d.vel * delta
		if n.position.x < FIELD.position.x: n.position.x = FIELD.end.x
		elif n.position.x > FIELD.end.x: n.position.x = FIELD.position.x
		if n.position.y < FIELD.position.y: n.position.y = FIELD.end.y
		elif n.position.y > FIELD.end.y: n.position.y = FIELD.position.y


# =============================================================================
#  End states
# =============================================================================
func _star_rating() -> int:
	var st := 1
	if stability >= 40.0: st += 1
	if stability >= 68.0: st += 1
	if stability >= 88.0: st += 1
	if elapsed_total() < 70.0 and stability >= 55.0: st += 1
	return clampi(st, 1, 5)


var _total_time := 0.0
func elapsed_total() -> float:
	return _total_time


func _victory() -> void:
	phase = Phase.VICTORY
	_total_time += elapsed
	var stars := _star_rating()
	score += stars * 100
	if record_on_win:
		_record(stars)
	var grade := "OPERATION COMPLETE" if stars >= 4 else "PATIENTS SAVED"
	_show_panel(
		grade,
		"All three patients stabilised.\nFinal stability  %d%%        Score  %d" % [int(stability), score],
		[{"text": "CONTINUE", "color": Color("2f9e5a"), "action": _leave},
		 {"text": "RETRY", "color": Color("3a78a8"), "action": _retry}],
		stars, Color("ffe08a"))


func _fail() -> void:
	phase = Phase.FAIL
	_flash_toast("", 0.01)
	_show_panel(
		"PATIENT CRITICAL",
		"Stability hit zero — the operation was aborted.\nSteady hands, Doctor. Try again.",
		[{"text": "RETRY", "color": Color("c1503e"), "action": _retry},
		 {"text": "LEAVE", "color": Color("3a78a8"), "action": _leave}],
		-1, Color("ff8a8a"))


func _retry() -> void:
	_clear_overlay()
	_clear_gameplay()
	_primary = Callable()
	_total_time = 0.0
	_start_run()


func _leave() -> void:
	if return_scene != "" and ResourceLoader.exists(return_scene):
		var sm = get_node_or_null("/root/SceneManager")
		if sm and sm.has_method("change_scene"):
			sm.change_scene(return_scene)
		else:
			get_tree().change_scene_to_file(return_scene)
	else:
		get_tree().reload_current_scene()


func _record(stars: int) -> void:
	var sm = get_node_or_null("/root/StarManager")
	if sm and sm.has_method("record_quest_stars"):
		var best := stars
		if sm.has_method("get_quest_stars"):
			best = max(stars, sm.get_quest_stars(quest_id))
		sm.record_quest_stars(quest_id, domain, best, 5)


# =============================================================================
#  Accept key triggers the primary overlay button
# =============================================================================
func _unhandled_input(event: InputEvent) -> void:
	if phase in [Phase.INTRO, Phase.INTERSTITIAL, Phase.VICTORY, Phase.FAIL]:
		if event.is_action_pressed("ui_accept") and _primary.is_valid():
			_primary.call()


# =============================================================================
#  FX + HUD helpers
# =============================================================================
func _spark(pos: Vector2, col: Color, burst := false) -> void:
	var s := Sprite2D.new()
	s.texture = _tex.get("spark")
	s.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST
	s.position = pos
	s.modulate = col
	s.z_index = 30
	play_root.add_child(s)
	var tw := s.create_tween().set_parallel(true)
	var drift := Vector2(randf_range(-30, 30), randf_range(-30, 30)) if burst else Vector2(0, -16)
	tw.tween_property(s, "position", pos + drift, 0.45)
	tw.tween_property(s, "scale", Vector2(0.2, 0.2), 0.45)
	tw.tween_property(s, "modulate:a", 0.0, 0.45)
	tw.chain().tween_callback(s.queue_free)


func _flash_toast(text: String, hold: float, col: Color = Color.WHITE) -> void:
	toast.text = text
	toast.add_theme_color_override("font_color", col)
	toast.modulate.a = 0.0
	if text == "":
		return
	var tw := toast.create_tween()
	tw.tween_property(toast, "modulate:a", 1.0, 0.18)
	tw.tween_interval(hold)
	tw.tween_property(toast, "modulate:a", 0.0, 0.4)


func _update_bar() -> void:
	if bar_fill == null:
		return
	var holder := bar_fill.get_parent()
	var w: float = holder.get_meta("w")
	var f := clampf(stability / 100.0, 0.0, 1.0)
	bar_fill.size.x = max(2.0, w * f)
	if f > 0.6:
		bar_fill.color = Color("4fd17a")
	elif f > 0.3:
		bar_fill.color = Color("e8c24a")
	else:
		bar_fill.color = Color("e0556a")


# ---- themed control factories (mirror the immune/xeno quest style) ----------
func _label(text: String, size: int, col: Color) -> Label:
	var l := Label.new()
	l.text = text
	l.add_theme_font_size_override("font_size", size)
	l.add_theme_color_override("font_color", col)
	return l


func _icon(tex_name: String, sz: int) -> TextureRect:
	var t := TextureRect.new()
	t.texture = _tex.get(tex_name)
	t.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST
	t.custom_minimum_size = Vector2(sz, sz)
	t.stretch_mode = TextureRect.STRETCH_KEEP_ASPECT_CENTERED
	t.size_flags_vertical = Control.SIZE_SHRINK_CENTER
	return t


func _panel(frame_name: String, margin: int) -> PanelContainer:
	var p := PanelContainer.new()
	p.add_theme_stylebox_override("panel", _frame_box(frame_name, margin))
	return p


func _frame_box(frame_name: String, content := 8, tmargin := 7) -> StyleBox:
	var tex: Texture2D = _tex.get(frame_name)
	if tex:
		var sb := StyleBoxTexture.new()
		sb.texture = tex
		sb.texture_margin_left = tmargin
		sb.texture_margin_top = tmargin
		sb.texture_margin_right = tmargin
		sb.texture_margin_bottom = tmargin
		sb.content_margin_left = content
		sb.content_margin_right = content
		sb.content_margin_top = content
		sb.content_margin_bottom = content
		return sb
	var f := StyleBoxFlat.new()
	f.bg_color = Color("1a0d12")
	f.border_color = Color("a83a4e")
	f.set_border_width_all(2)
	return f


func _button(text: String, col: Color) -> Button:
	var b := Button.new()
	b.text = text
	b.focus_mode = Control.FOCUS_NONE
	b.add_theme_stylebox_override("normal", _button_box(col))
	b.add_theme_stylebox_override("hover", _button_box(col.lightened(0.16)))
	b.add_theme_stylebox_override("pressed", _button_box(col.darkened(0.2)))
	b.add_theme_color_override("font_color", Color("f7fffb"))
	b.add_theme_color_override("font_hover_color", Color("ffffff"))
	b.add_theme_font_size_override("font_size", 20)
	return b


func _button_box(col: Color) -> StyleBox:
	var tex: Texture2D = _tex.get("button")
	if tex:
		var sb := StyleBoxTexture.new()
		sb.texture = tex
		sb.modulate_color = col
		sb.texture_margin_left = 5
		sb.texture_margin_top = 5
		sb.texture_margin_right = 5
		sb.texture_margin_bottom = 5
		sb.content_margin_left = 22
		sb.content_margin_right = 22
		sb.content_margin_top = 10
		sb.content_margin_bottom = 10
		return sb
	var f := StyleBoxFlat.new()
	f.bg_color = col.darkened(0.15)
	f.border_color = col.lightened(0.25)
	f.set_border_width_all(2)
	return f


# =============================================================================
#  Radial repair gauges (drawn above the breach sprites)
# =============================================================================
class _Gauge extends Node2D:
	var quest

	func _draw() -> void:
		if quest == null:
			return
		for s in quest.sites:
			if s.healed:
				continue
			var p: Vector2 = s.pos
			# attention ring on every open breach (subtle pulse)
			var pulse := 0.5 + 0.5 * sin(Time.get_ticks_msec() / 220.0)
			draw_arc(p, 28.0, 0, TAU, 40, Color(1.0, 0.35, 0.4, 0.25 + pulse * 0.2), 2.0, true)
			if s.progress > 0.0:
				draw_arc(p, 30.0, 0, TAU, 40, Color(0.1, 0.4, 0.42, 0.6), 4.0, true)
				draw_arc(p, 30.0, -PI / 2, -PI / 2 + s.progress * TAU, 48,
						Color(0.56, 0.96, 0.92, 0.95), 4.0, true)
