# EndingCutscene.gd
# Dynamic, pixel-art ending. A parallax "renaissance village" panorama (sky,
# god-rays, hills, drifting clouds, village, foreground, embers, birds, fireworks)
# carries a condensed THREE-slide finale:
#   1. RENAISSANCE - ending-tier title over a ribbon, the five domain medallions
#                    arc in with a sparkle pop, each showing its stars.
#   2. LEGACY      - a compact stats dashboard: total stars count up, quests,
#                    an achievement bar that fills, medallions in a tidy row.
#   3. FAREWELL    - the Shifter raises a hand on the hill, fireworks bloom, and
#                    a short credits card thanks the player.
# All art is generated by tools/make_ending.py into assets/generated/ending/.
# Attach to the CanvasLayer root of EndingCutscene.tscn.

extends CanvasLayer

# ----------------------------------------------------------------- exports --
@export_group("Customization")
@export var custom_font: Font
@export var title_font_size: int = 54
@export var subtitle_font_size: int = 28
@export var body_font_size: int = 20
@export var fade_speed: float = 2.0

# ----------------------------------------------------------------- constants -
const ART := "res://assets/generated/ending/"
const W := 1152.0
const H := 648.0
const SUN := Vector2(461, 300)                 # sun centre on screen (art 0.40w)
const HERO_X := 250.0                           # hero stands left of the centred credits
const DOMAINS := ["Engineering", "Farming", "Leadership", "Medicine", "Art"]
const ACCENT := {
	"Engineering": Color("f4c12e"),
	"Farming":     Color("5fc85a"),
	"Leadership":  Color("3f8cf0"),
	"Medicine":    Color("a25bf0"),
	"Art":         Color("e8554e"),
}
const TAGLINE := {
	"perfect":   "Five domains. One legend. A village remade in gold.",
	"excellent": "Master of many crafts — your village shines for ages.",
	"good":      "A new golden age dawns over the village you rebuilt.",
	"decent":    "Real change has taken root. Hope grows in every field.",
	"poor":      "The first steps are taken — the village's story begins.",
}

enum Slide { FADE_IN, RENAISSANCE, LEGACY, FAREWELL, FADE_OUT }

# ----------------------------------------------------------------- state -----
var slide: int = Slide.FADE_IN
var busy: bool = true
var prompt_ready: bool = false

var ending_info: Dictionary
var ending_stats: Dictionary

# nodes
var tex_cache: Dictionary = {}
var fade_overlay: ColorRect
var rays: Sprite2D
var clouds: TextureRect
var hero: Sprite2D
var content: Control
var text_panel: ColorRect
var title_label: Label
var subtitle_label: Label
var body_label: RichTextLabel
var continue_prompt: Label
var banner: TextureRect
var legacy_total: Label
var legacy_quests: Label
var bar_track: ColorRect
var bar_fill: ColorRect
var bar_label: Label
var emblem_sprites: Array = []
var emblem_labels: Array = []


# ================================================================= lifecycle =
func _ready():
	print("[EndingCutscene] pixel-art finale starting")
	layer = 100
	visible = true

	ending_info = EndingManager.get_ending_info()
	ending_stats = EndingManager.get_ending_statistics()

	_build()
	await get_tree().process_frame

	LegacyAchievementManager.check_star_achievements()
	if EndingManager.check_all_quests_complete():
		LegacyAchievementManager.unlock_achievement("complete_collection")

	_start()


func _process(delta):
	if is_instance_valid(rays):
		rays.rotation += delta * 0.045         # slow, hypnotic god-rays


func _input(event):
	if event.is_action_pressed("ui_accept") and prompt_ready and not busy:
		_advance()


# ===================================================================== build =
func _build():
	# --- never-black fallback (in case generated art is missing) ---
	var solid := ColorRect.new()
	solid.color = Color("241b3e")
	solid.anchor_right = 1.0; solid.anchor_bottom = 1.0
	solid.z_index = -300
	solid.mouse_filter = Control.MOUSE_FILTER_IGNORE
	add_child(solid)

	# --- parallax panorama ---
	_bg_layer("sky", -200)
	_make_rays()
	_bg_layer("hills", -120)
	_make_clouds()
	_bg_layer("village", -110)
	_bg_layer("foreground", -100)
	_make_twinkles()
	_make_embers()
	_make_birds()
	_make_hero()

	# --- content overlay ---
	content = Control.new()
	content.anchor_right = 1.0; content.anchor_bottom = 1.0
	content.mouse_filter = Control.MOUSE_FILTER_IGNORE
	content.z_index = 10
	add_child(content)

	# translucent plate behind paragraph text for legibility
	text_panel = ColorRect.new()
	text_panel.color = Color(0.05, 0.03, 0.10, 0.46)
	text_panel.anchor_left = 0.18; text_panel.anchor_right = 0.82
	text_panel.anchor_top = 0.30; text_panel.anchor_bottom = 0.74
	text_panel.mouse_filter = Control.MOUSE_FILTER_IGNORE
	text_panel.modulate.a = 0.0
	content.add_child(text_panel)

	# title banner ribbon (placed, not stretched)
	banner = TextureRect.new()
	banner.texture = _tex("banner")
	banner.expand_mode = TextureRect.EXPAND_IGNORE_SIZE
	banner.stretch_mode = TextureRect.STRETCH_KEEP_ASPECT_CENTERED
	banner.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST
	banner.mouse_filter = Control.MOUSE_FILTER_IGNORE
	banner.custom_minimum_size = Vector2(720, 150)
	banner.size = Vector2(720, 150)
	banner.position = Vector2(W / 2 - 360, 96)
	banner.pivot_offset = Vector2(360, 75)
	banner.scale = Vector2.ZERO
	banner.modulate.a = 0.0
	content.add_child(banner)

	title_label = _make_label(title_font_size, HORIZONTAL_ALIGNMENT_CENTER)
	title_label.anchor_left = 0.5; title_label.anchor_right = 0.5
	title_label.offset_left = -520; title_label.offset_right = 520
	title_label.offset_top = 120; title_label.offset_bottom = 200
	content.add_child(title_label)

	subtitle_label = _make_label(subtitle_font_size, HORIZONTAL_ALIGNMENT_CENTER)
	subtitle_label.anchor_left = 0.5; subtitle_label.anchor_right = 0.5
	subtitle_label.offset_left = -500; subtitle_label.offset_right = 500
	subtitle_label.offset_top = 206; subtitle_label.offset_bottom = 250
	content.add_child(subtitle_label)

	body_label = RichTextLabel.new()
	body_label.bbcode_enabled = true
	body_label.fit_content = true
	body_label.scroll_active = false
	body_label.anchor_left = 0.2; body_label.anchor_right = 0.8
	body_label.anchor_top = 0.40; body_label.anchor_bottom = 0.70
	body_label.mouse_filter = Control.MOUSE_FILTER_IGNORE
	body_label.add_theme_font_size_override("normal_font_size", body_font_size)
	body_label.add_theme_color_override("default_color", Color("fdeccb"))
	if custom_font:
		body_label.add_theme_font_override("normal_font", custom_font)
		body_label.add_theme_font_override("bold_font", custom_font)
	body_label.modulate.a = 0.0
	content.add_child(body_label)

	# --- legacy dashboard widgets (hidden until slide 2) ---
	legacy_total = _make_label(56, HORIZONTAL_ALIGNMENT_CENTER)
	legacy_total.anchor_right = 1.0
	legacy_total.offset_top = 330; legacy_total.offset_bottom = 410
	legacy_total.add_theme_color_override("font_color", Color("ffd86a"))
	legacy_total.modulate.a = 0.0
	content.add_child(legacy_total)

	legacy_quests = _make_label(26, HORIZONTAL_ALIGNMENT_CENTER)
	legacy_quests.anchor_right = 1.0
	legacy_quests.offset_top = 410; legacy_quests.offset_bottom = 446
	legacy_quests.add_theme_color_override("font_color", Color("fdeccb"))
	legacy_quests.modulate.a = 0.0
	content.add_child(legacy_quests)

	bar_track = ColorRect.new()
	bar_track.color = Color("181226")
	bar_track.size = Vector2(560, 26)
	bar_track.position = Vector2(W / 2 - 280, 470)
	bar_track.mouse_filter = Control.MOUSE_FILTER_IGNORE
	bar_track.modulate.a = 0.0
	var border := ColorRect.new()              # dark pixel border
	border.color = Color("0c0814")
	border.size = Vector2(568, 34)
	border.position = Vector2(W / 2 - 284, 466)
	border.mouse_filter = Control.MOUSE_FILTER_IGNORE
	border.modulate.a = 0.0
	border.name = "BarBorder"
	content.add_child(border)
	content.add_child(bar_track)
	bar_fill = ColorRect.new()
	bar_fill.color = Color("4fd08a")
	bar_fill.size = Vector2(0, 26)
	bar_fill.position = bar_track.position
	bar_fill.mouse_filter = Control.MOUSE_FILTER_IGNORE
	content.add_child(bar_fill)
	bar_label = _make_label(18, HORIZONTAL_ALIGNMENT_CENTER)
	bar_label.anchor_right = 1.0
	bar_label.offset_top = 472; bar_label.offset_bottom = 496
	bar_label.modulate.a = 0.0
	content.add_child(bar_label)

	# --- five domain medallions ---
	for i in DOMAINS.size():
		var domain: String = DOMAINS[i]
		var sp := Sprite2D.new()
		sp.texture = _tex("emblem_" + domain.to_lower())
		sp.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST
		sp.position = _arc_point(i)
		sp.scale = Vector2.ZERO
		sp.modulate.a = 0.0
		sp.z_index = 12
		content.add_child(sp)
		emblem_sprites.append(sp)

		var lbl := _make_label(20, HORIZONTAL_ALIGNMENT_CENTER)
		lbl.size = Vector2(200, 28)
		lbl.custom_minimum_size = Vector2(200, 28)
		lbl.add_theme_color_override("font_color", ACCENT[domain])
		lbl.modulate.a = 0.0
		content.add_child(lbl)
		emblem_labels.append(lbl)

	# --- continue prompt ---
	continue_prompt = _make_label(18, HORIZONTAL_ALIGNMENT_CENTER)
	continue_prompt.anchor_right = 1.0
	continue_prompt.offset_top = 588; continue_prompt.offset_bottom = 620
	continue_prompt.text = "▸  Press SPACE to continue"
	continue_prompt.add_theme_color_override("font_color", Color("ffd07a"))
	continue_prompt.modulate.a = 0.0
	content.add_child(continue_prompt)

	# --- fade-from-black overlay, on top of everything ---
	fade_overlay = ColorRect.new()
	fade_overlay.color = Color(0, 0, 0)
	fade_overlay.anchor_right = 1.0; fade_overlay.anchor_bottom = 1.0
	fade_overlay.z_index = 1000
	fade_overlay.mouse_filter = Control.MOUSE_FILTER_IGNORE
	add_child(fade_overlay)


# ----------------------------------------------------------- build helpers ---
func _tex(n: String) -> Texture2D:
	if tex_cache.has(n):
		return tex_cache[n]
	var p := ART + n + ".png"
	var t: Texture2D = load(p) if ResourceLoader.exists(p) else null
	tex_cache[n] = t
	return t


func _bg_layer(n: String, z: int) -> TextureRect:
	var tr := TextureRect.new()
	tr.texture = _tex(n)
	tr.anchor_right = 1.0; tr.anchor_bottom = 1.0
	tr.expand_mode = TextureRect.EXPAND_IGNORE_SIZE
	tr.stretch_mode = TextureRect.STRETCH_SCALE
	tr.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST
	tr.mouse_filter = Control.MOUSE_FILTER_IGNORE
	tr.z_index = z
	add_child(tr)
	return tr


func _make_label(size: int, align: int) -> Label:
	var l := Label.new()
	l.horizontal_alignment = align
	l.vertical_alignment = VERTICAL_ALIGNMENT_CENTER
	l.autowrap_mode = TextServer.AUTOWRAP_WORD
	l.mouse_filter = Control.MOUSE_FILTER_IGNORE
	l.add_theme_font_size_override("font_size", size)
	l.add_theme_color_override("font_color", Color("fdeccb"))
	l.add_theme_color_override("font_outline_color", Color(0.04, 0.02, 0.08))
	l.add_theme_constant_override("outline_size", 8)
	l.add_theme_color_override("font_shadow_color", Color(0, 0, 0, 0.5))
	l.add_theme_constant_override("shadow_offset_x", 2)
	l.add_theme_constant_override("shadow_offset_y", 3)
	if custom_font:
		l.add_theme_font_override("font", custom_font)
	return l


func _make_rays():
	rays = Sprite2D.new()
	rays.texture = _tex("rays")
	if rays.texture == null:
		return
	rays.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST
	rays.position = SUN
	rays.scale = Vector2(3.4, 3.4)
	rays.modulate = Color(1, 1, 1, 0.55)
	rays.z_index = -150
	var m := CanvasItemMaterial.new()
	m.blend_mode = CanvasItemMaterial.BLEND_MODE_ADD
	rays.material = m
	add_child(rays)


func _make_clouds():
	clouds = TextureRect.new()
	clouds.texture = _tex("clouds")
	clouds.expand_mode = TextureRect.EXPAND_IGNORE_SIZE
	clouds.stretch_mode = TextureRect.STRETCH_SCALE
	clouds.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST
	clouds.mouse_filter = Control.MOUSE_FILTER_IGNORE
	clouds.size = Vector2(1536, 348)
	clouds.position = Vector2(-300, 24)
	clouds.z_index = -130
	clouds.modulate.a = 0.92
	add_child(clouds)
	var t := create_tween().set_loops()
	t.tween_property(clouds, "position:x", -120, 62.0).set_trans(Tween.TRANS_SINE).set_ease(Tween.EASE_IN_OUT)
	t.tween_property(clouds, "position:x", -300, 62.0).set_trans(Tween.TRANS_SINE).set_ease(Tween.EASE_IN_OUT)


func _make_twinkles():
	var spark := _tex("sparkle")
	if spark == null:
		return
	var rng := RandomNumberGenerator.new()
	rng.seed = 7
	for i in 16:
		var s := Sprite2D.new()
		s.texture = spark
		s.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST
		s.position = Vector2(rng.randf_range(40, W - 40), rng.randf_range(30, 210))
		s.scale = Vector2(rng.randf_range(0.7, 1.5), rng.randf_range(0.7, 1.5))
		s.modulate = Color(1, 1, 1, rng.randf_range(0.2, 0.7))
		s.z_index = -140
		var m := CanvasItemMaterial.new()
		m.blend_mode = CanvasItemMaterial.BLEND_MODE_ADD
		s.material = m
		add_child(s)
		var t := create_tween().set_loops()
		var dur := rng.randf_range(1.1, 2.4)
		t.tween_property(s, "modulate:a", 0.9, dur).set_trans(Tween.TRANS_SINE)
		t.tween_property(s, "modulate:a", 0.12, dur).set_trans(Tween.TRANS_SINE)


func _make_embers():
	var p := CPUParticles2D.new()
	p.texture = _tex("sparkle")
	p.position = Vector2(W / 2, H * 0.85)
	p.amount = 34
	p.lifetime = 6.5
	p.preprocess = 3.0
	p.z_index = -50
	p.emission_shape = CPUParticles2D.EMISSION_SHAPE_RECTANGLE
	p.emission_rect_extents = Vector2(W / 2, 90)
	p.direction = Vector2(0, -1)
	p.spread = 24.0
	p.gravity = Vector2(0, -9)
	p.initial_velocity_min = 5.0
	p.initial_velocity_max = 20.0
	p.scale_amount_min = 0.5
	p.scale_amount_max = 1.6
	p.color = Color("ffdca0")
	var g := Gradient.new()
	g.set_color(0, Color(1, 0.86, 0.55, 0.0))
	g.set_color(1, Color(1, 0.86, 0.55, 0.0))
	g.add_point(0.25, Color(1, 0.9, 0.6, 0.85))
	g.add_point(0.7, Color(1, 0.82, 0.5, 0.6))
	p.color_ramp = g
	var m := CanvasItemMaterial.new()
	m.blend_mode = CanvasItemMaterial.BLEND_MODE_ADD
	p.material = m
	p.emitting = true
	add_child(p)


func _make_birds():
	var bt := _tex("bird")
	if bt == null:
		return
	var rng := RandomNumberGenerator.new()
	rng.seed = 99
	for i in 3:
		var b := Sprite2D.new()
		b.texture = bt
		b.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST
		b.scale = Vector2(2.4, 2.4)
		b.modulate = Color(1, 1, 1, 0.85)
		b.z_index = -125
		add_child(b)
		_fly_bird(b, rng, float(i) * 5.0 + rng.randf_range(0.0, 4.0))


func _fly_bird(b: Sprite2D, rng: RandomNumberGenerator, delay: float):
	var y := rng.randf_range(70, 200)
	b.position = Vector2(-60, y)
	var dur := rng.randf_range(15.0, 22.0)
	var t := create_tween().set_loops()
	t.tween_interval(delay)
	t.tween_callback(func(): b.position = Vector2(-60, rng.randf_range(60, 210)))
	t.tween_property(b, "position:x", W + 80, dur).set_trans(Tween.TRANS_LINEAR)
	t.tween_interval(rng.randf_range(4.0, 9.0))


func _make_hero():
	hero = Sprite2D.new()
	hero.texture = _tex("hero")
	if hero.texture == null:
		return
	hero.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST
	hero.scale = Vector2(3, 3)
	hero.position = Vector2(HERO_X, H - 60)
	hero.modulate.a = 0.0
	hero.z_index = -90
	add_child(hero)


# ----------------------------------------------------------- emblem layout ---
func _arc_point(i: int) -> Vector2:
	var x: float = lerp(190.0, 962.0, i / 4.0)
	var y: float = 432.0 - 30.0 * sin(PI * i / 4.0)   # gentle upward arc
	return Vector2(x, y)


func _row_point(i: int) -> Vector2:
	return Vector2(lerp(210.0, 942.0, i / 4.0), 250.0)


func _place_label_under(i: int, centre: Vector2, emblem_scale: float):
	var lbl: Label = emblem_labels[i]
	lbl.position = Vector2(centre.x - 100, centre.y + 22.0 * emblem_scale + 6.0)


# ================================================================ sequencing =
func _start():
	slide = Slide.FADE_IN
	var t := create_tween()
	t.tween_property(fade_overlay, "modulate:a", 0.0, fade_speed * 1.4).set_ease(Tween.EASE_IN_OUT)
	await t.finished
	_play_renaissance()


func _advance():
	prompt_ready = false
	match slide:
		Slide.RENAISSANCE:
			await _wipe_text()
			_play_legacy()
		Slide.LEGACY:
			await _wipe_text()
			await _hide_emblems()
			_play_farewell()
		Slide.FAREWELL:
			_fade_out()


func _wipe_text():
	busy = true
	var t := create_tween()
	t.set_parallel(true)
	for n in [title_label, subtitle_label, body_label, continue_prompt, text_panel,
			banner, legacy_total, legacy_quests, bar_label]:
		t.tween_property(n, "modulate:a", 0.0, 0.4)
	t.tween_property(bar_track, "modulate:a", 0.0, 0.4)
	t.tween_property(bar_fill, "modulate:a", 0.0, 0.4)
	var bb := content.get_node_or_null("BarBorder")
	if bb:
		t.tween_property(bb, "modulate:a", 0.0, 0.4)
	await t.finished
	await get_tree().create_timer(0.15).timeout


func _hide_emblems():
	var t := create_tween()
	t.set_parallel(true)
	for i in emblem_sprites.size():
		t.tween_property(emblem_sprites[i], "modulate:a", 0.0, 0.4)
		t.tween_property(emblem_sprites[i], "scale", Vector2(0.1, 0.1), 0.4)
		t.tween_property(emblem_labels[i], "modulate:a", 0.0, 0.4)
	await t.finished


func _show_prompt(text: String = "▸  Press SPACE to continue"):
	continue_prompt.text = text
	var t := create_tween()
	t.tween_property(continue_prompt, "modulate:a", 0.9, 0.5)
	await t.finished
	# gentle pulse
	var p := create_tween().set_loops()
	p.tween_property(continue_prompt, "modulate:a", 0.45, 0.9).set_trans(Tween.TRANS_SINE)
	p.tween_property(continue_prompt, "modulate:a", 0.95, 0.9).set_trans(Tween.TRANS_SINE)
	busy = false
	prompt_ready = true


# ----------------------------------------------------------- title layout ---
func _completion_pct() -> float:
	# Overall completion is driven by the stars actually collected, so the % the
	# player reads always agrees with the "★ x / y" total. (Achievement unlocks
	# are a separate axis and many never trigger in normal play, which is why the
	# old achievement-based percentage looked wrong next to the stars.)
	var total: int = ending_stats.get("total_stars", StarManager.get_total_stars())
	var maxs: int = ending_stats.get("max_possible_stars", 75)
	if maxs <= 0:
		return 0.0
	return 100.0 * float(total) / float(maxs)


func _reset_title_layout():
	# Wide, screen-centred title for the slides that have no ribbon banner.
	title_label.add_theme_font_size_override("font_size", title_font_size)
	title_label.offset_left = -520; title_label.offset_right = 520
	title_label.offset_top = 120; title_label.offset_bottom = 200


func _layout_title_in_banner():
	# Sit the title inside the ribbon's writable plate, centred both ways, and
	# shrink the font until even the longest tier title ("The Perfect
	# Renaissance") fits between the studs instead of spilling past the ribbon.
	title_label.offset_left = -275; title_label.offset_right = 275
	title_label.offset_top = 141; title_label.offset_bottom = 206
	var fit: int = title_font_size
	var font: Font = title_label.get_theme_font("font")
	if font:
		while fit > 22 and font.get_string_size(
				title_label.text, HORIZONTAL_ALIGNMENT_LEFT, -1, fit).x > 510.0:
			fit -= 2
	title_label.add_theme_font_size_override("font_size", fit)


# -------------------------------------------------------- SLIDE 1: title ----
func _play_renaissance():
	slide = Slide.RENAISSANCE
	busy = true

	var tier: String = ending_info.get("tier", "good")
	title_label.text = ending_info.get("title", "The Renaissance")
	title_label.add_theme_color_override("font_color", ending_info.get("color", Color("ffd86a")))
	_layout_title_in_banner()
	subtitle_label.text = ending_info.get("subtitle", "")
	subtitle_label.add_theme_color_override("font_color", Color("ffe6b0"))
	# Drop the prose clear of the banner so it reads as its own block instead of
	# being crowded up into the ribbon (the banner ends at ~y246).
	subtitle_label.offset_top = 256; subtitle_label.offset_bottom = 300
	body_label.anchor_top = 0.49
	body_label.text = "[center]" + TAGLINE.get(tier, ending_info.get("subtitle", "")) + "[/center]"

	# banner pops, then title + subtitle rise
	var t := create_tween()
	t.tween_property(banner, "modulate:a", 1.0, 0.3)
	t.parallel().tween_property(banner, "scale", Vector2(1, 1), 0.6) \
		.set_trans(Tween.TRANS_BACK).set_ease(Tween.EASE_OUT)
	await t.finished

	var t2 := create_tween()
	t2.tween_property(title_label, "modulate:a", 1.0, 0.6).set_ease(Tween.EASE_OUT)
	t2.tween_property(subtitle_label, "modulate:a", 1.0, 0.5).set_ease(Tween.EASE_OUT)
	t2.parallel().tween_property(text_panel, "modulate:a", 1.0, 0.5)
	t2.tween_property(body_label, "modulate:a", 1.0, 0.5).set_ease(Tween.EASE_OUT)
	await t2.finished

	# medallions arc in one by one with a pop + sparkle + star count
	for i in DOMAINS.size():
		var domain: String = DOMAINS[i]
		var centre := _arc_point(i)
		emblem_sprites[i].position = centre
		var stars: int = StarManager.get_domain_stars(domain)
		emblem_labels[i].text = "%s  %d★" % [domain, stars]
		_place_label_under(i, centre, 1.6)
		var et := create_tween()
		et.tween_property(emblem_sprites[i], "modulate:a", 1.0, 0.25)
		et.parallel().tween_property(emblem_sprites[i], "scale", Vector2(1.6, 1.6), 0.5) \
			.set_trans(Tween.TRANS_BACK).set_ease(Tween.EASE_OUT)
		et.parallel().tween_property(emblem_labels[i], "modulate:a", 1.0, 0.4)
		_burst(centre, ACCENT[domain], 12, 130, 0.7)
		await get_tree().create_timer(0.22).timeout
	await get_tree().create_timer(0.2).timeout

	await _show_prompt()


# -------------------------------------------------------- SLIDE 2: legacy ----
func _play_legacy():
	slide = Slide.LEGACY
	busy = true

	title_label.text = "Your Legacy"
	title_label.add_theme_color_override("font_color", Color("ffd86a"))
	_reset_title_layout()
	title_label.modulate.a = 0.0
	subtitle_label.text = ""

	# medallions glide up into a tidy row, now showing per-domain stars
	var t := create_tween()
	t.set_parallel(true)
	t.tween_property(title_label, "modulate:a", 1.0, 0.6)
	for i in DOMAINS.size():
		var domain: String = DOMAINS[i]
		var centre := _row_point(i)
		var ds: Dictionary = ending_stats.get("domain_stats", {}).get(domain, {})
		var stars: int = ds.get("stars", StarManager.get_domain_stars(domain))
		var maxs: int = ds.get("max_stars", 15)
		emblem_labels[i].text = "%d / %d ★" % [stars, maxs]
		_place_label_under(i, centre, 1.45)
		emblem_sprites[i].modulate.a = 1.0
		emblem_labels[i].modulate.a = 1.0
		t.tween_property(emblem_sprites[i], "position", centre, 0.6).set_trans(Tween.TRANS_CUBIC)
		t.tween_property(emblem_sprites[i], "scale", Vector2(1.45, 1.45), 0.6)
	await t.finished

	# big total-stars count-up
	var total: int = ending_stats.get("total_stars", StarManager.get_total_stars())
	var maxstars: int = ending_stats.get("max_possible_stars", 75)
	legacy_total.text = "★ 0 / %d" % maxstars
	var t2 := create_tween()
	t2.tween_property(legacy_total, "modulate:a", 1.0, 0.4)
	t2.parallel().tween_method(
		func(v): legacy_total.text = "★ %d / %d" % [int(round(v)), maxstars],
		0.0, float(total), 1.4).set_trans(Tween.TRANS_CUBIC)
	await t2.finished
	_burst(Vector2(W / 2, 366), Color("ffd86a"), 22, 200, 1.0)

	# quests + achievement bar
	var qc: int = ending_stats.get("quests_completed", 0)
	var qt: int = ending_stats.get("total_quests", 15)
	legacy_quests.text = "Quests Completed:  %d / %d" % [qc, qt]
	var pct: float = _completion_pct()
	bar_label.text = "Completion  %d%%" % int(round(pct))
	bar_fill.size.x = 0.0                       # restore fill (wiped during transition)
	bar_fill.modulate.a = 1.0
	var bb := content.get_node_or_null("BarBorder")
	var t3 := create_tween()
	t3.set_parallel(true)
	t3.tween_property(legacy_quests, "modulate:a", 1.0, 0.5)
	if bb:
		t3.tween_property(bb, "modulate:a", 1.0, 0.5)
	t3.tween_property(bar_track, "modulate:a", 1.0, 0.5)
	t3.tween_property(bar_label, "modulate:a", 1.0, 0.5)
	await t3.finished
	var t4 := create_tween()
	t4.tween_property(bar_fill, "size:x", 560.0 * clampf(pct / 100.0, 0.0, 1.0), 1.0) \
		.set_trans(Tween.TRANS_CUBIC).set_ease(Tween.EASE_OUT)
	await t4.finished

	await _show_prompt()


# ------------------------------------------------------- SLIDE 3: farewell ---
func _play_farewell():
	slide = Slide.FAREWELL
	busy = true

	# legacy widgets out
	var clr := create_tween()
	clr.set_parallel(true)
	for n in [legacy_total, legacy_quests, bar_label, bar_track, bar_fill]:
		clr.tween_property(n, "modulate:a", 0.0, 0.3)
	var bb := content.get_node_or_null("BarBorder")
	if bb:
		clr.tween_property(bb, "modulate:a", 0.0, 0.3)
	await clr.finished

	# the Shifter rises on the hill, hand raised
	if is_instance_valid(hero):
		hero.position = Vector2(HERO_X, H - 36)
		var ht := create_tween()
		ht.tween_property(hero, "modulate:a", 1.0, 0.8)
		ht.parallel().tween_property(hero, "position:y", H - 60, 0.8).set_trans(Tween.TRANS_BACK).set_ease(Tween.EASE_OUT)
		await ht.finished
		# gentle idle bob
		var bob := create_tween().set_loops()
		bob.tween_property(hero, "position:y", H - 66, 1.3).set_trans(Tween.TRANS_SINE)
		bob.tween_property(hero, "position:y", H - 60, 1.3).set_trans(Tween.TRANS_SINE)

	_fireworks()

	title_label.text = "Thank You"
	title_label.add_theme_color_override("font_color", Color("ffd86a"))
	_reset_title_layout()
	title_label.offset_top = 92; title_label.offset_bottom = 172
	title_label.modulate.a = 0.0
	subtitle_label.text = "— The Village Will Remember You —"
	subtitle_label.add_theme_color_override("font_color", Color("ffe6b0"))
	subtitle_label.offset_top = 206; subtitle_label.offset_bottom = 250  # sits below the raised "Thank You", above credits
	subtitle_label.modulate.a = 0.0

	var total: int = ending_stats.get("total_stars", 0)
	var maxstars: int = ending_stats.get("max_possible_stars", 75)
	var qc: int = ending_stats.get("quests_completed", 0)
	var qt: int = ending_stats.get("total_quests", 15)
	var pct: float = _completion_pct()
	body_label.offset_left = 0  # widen
	body_label.anchor_left = 0.16; body_label.anchor_right = 0.84
	body_label.anchor_top = 0.40; body_label.anchor_bottom = 0.78
	body_label.text = ("[center][font_size=30]Career Realms: The Shifter's Path[/font_size]\n\n"
		+ "Owen Liu   •   Ryan Tang   •   Jathon Chen\n\n"
		+ "[font_size=18]Made with the Godot Engine[/font_size]\n\n"
		+ "★ %d / %d Stars     ·     %d / %d Quests     ·     %d%% Complete\n\n\n"
		+ "[font_size=26]Thanks for playing![/font_size][/center]") % [total, maxstars, qc, qt, int(round(pct))]

	var t := create_tween()
	t.tween_property(text_panel, "modulate:a", 1.0, 0.5)
	t.parallel().tween_property(title_label, "modulate:a", 1.0, 0.7).set_ease(Tween.EASE_OUT)
	t.tween_property(subtitle_label, "modulate:a", 1.0, 0.6)
	t.tween_property(body_label, "modulate:a", 1.0, 0.8).set_ease(Tween.EASE_OUT)
	await t.finished
	await get_tree().create_timer(0.4).timeout

	await _show_prompt("▸  Press SPACE to return to the village")


func _fireworks():
	# repeated coloured bursts over the skyline until the slide ends
	var rng := RandomNumberGenerator.new()
	rng.randomize()
	var keys := ACCENT.keys()
	var timer := Timer.new()
	timer.wait_time = 0.65
	timer.autostart = true
	add_child(timer)
	timer.timeout.connect(func():
		if slide != Slide.FAREWELL or not is_instance_valid(self):
			timer.stop(); timer.queue_free(); return
		var pos := Vector2(rng.randf_range(W * 0.2, W * 0.8), rng.randf_range(110, 320))
		_burst(pos, ACCENT[keys[rng.randi() % keys.size()]], 26, 230, 1.1, 150.0)
	)


# --------------------------------------------------------------- particles ---
func _burst(pos: Vector2, col: Color, amount: int, speed: float, life: float, grav: float = 0.0):
	var p := CPUParticles2D.new()
	p.texture = _tex("sparkle")
	p.position = pos
	p.one_shot = true
	p.explosiveness = 1.0
	p.amount = amount
	p.lifetime = life
	p.z_index = 40
	p.direction = Vector2(0, -1)
	p.spread = 180.0
	p.gravity = Vector2(0, grav)
	p.initial_velocity_min = speed * 0.35
	p.initial_velocity_max = speed
	p.scale_amount_min = 1.0
	p.scale_amount_max = 2.6
	p.color = col
	var g := Gradient.new()
	g.set_color(0, Color(col.r, col.g, col.b, 1.0))
	g.set_color(1, Color(col.r, col.g, col.b, 0.0))
	p.color_ramp = g
	var m := CanvasItemMaterial.new()
	m.blend_mode = CanvasItemMaterial.BLEND_MODE_ADD
	p.material = m
	p.emitting = true
	add_child(p)
	var life_timer := get_tree().create_timer(life + 0.4)
	life_timer.timeout.connect(func():
		if is_instance_valid(p):
			p.queue_free()
	)


# ----------------------------------------------------------------- fade out --
func _fade_out():
	slide = Slide.FADE_OUT
	busy = true
	prompt_ready = false
	fade_overlay.z_index = 2000
	fade_overlay.modulate.a = 0.0
	var t := create_tween()
	t.tween_property(fade_overlay, "modulate:a", 1.0, fade_speed * 1.4).set_ease(Tween.EASE_IN)
	await t.finished
	get_tree().change_scene_to_file("res://scenes/maps/MainHub.tscn")
