# IntroCutscene.gd
# A short, cinematic, pixel-art intro played after "New Game". Three animated
# beats on the same living world as the title screen (parallax sky, drifting
# clouds, a glowing RIFT, a fantasy skyline, a hilltop):
#   1. THE GOLDEN AGE - the five realms glow; the Shifters could move between all.
#   2. THE FRACTURE   - the sky cracks (flash + screen shake), the world dims and
#                       the realm emblems scatter dark.
#   3. THE LAST SHIFTER - dawn returns, the hero rises before the rift, the realms
#                       wait to be reclaimed -> fade to the hub.
# Narration sits in a pixel caption bar. SPACE/ENTER advances, ESC skips.
# Art is generated by tools/make_title.py into assets/generated/title/.
# Attach to the CanvasLayer root of IntroCutscene.tscn.

extends CanvasLayer

@export var custom_font: Font

const ART := "res://assets/generated/title/"
const W := 1152.0
const H := 648.0
const RIFT := Vector2(576, 244)
const DOMAINS := ["Engineering", "Farming", "Leadership", "Medicine", "Art"]
const ACCENT := {
	"Engineering": Color("f4c12e"), "Farming": Color("5fc85a"),
	"Leadership": Color("3f8cf0"), "Medicine": Color("a25bf0"), "Art": Color("e8554e"),
}

# the three beats
const BEATS := [
	{
		"title": "An Age of Many Paths",
		"color": "ffd86a",
		"text": "[center]Long ago, the [b]Shifters[/b] could move freely between the five realms — "
			+ "[color=#f4c12e]Engineering[/color], [color=#5fc85a]Farming[/color], "
			+ "[color=#3f8cf0]Leadership[/color], [color=#a25bf0]Medicine[/color] and "
			+ "[color=#e8554e]Art[/color].  They built wonders.[/center]",
	},
	{
		"title": "The Fracture",
		"color": "e8554e",
		"text": "[center]Then the sky broke.  The paths between the realms [b]shattered[/b] — "
			+ "and the world forgot how to shift.[/center]",
	},
	{
		"title": "The Last Shifter",
		"color": "9ef0ff",
		"text": "[center]You are the [b]last Shifter[/b].  Reconnect the five realms, earn their stars, "
			+ "and bring the world back to light.[/center]",
	},
]

# nodes / state
var tex_cache: Dictionary = {}
var parallax_layers: Array = []
var rift: Sprite2D
var rays: Sprite2D
var sun: Sprite2D                                   # warm bloom (golden age / dawn)
var hero: Sprite2D
var staff_glow: Sprite2D                            # light at the Shifter's staff
var emblem_sprites: Array = []
var emblem_halos: Array = []
var dim: ColorRect                                  # cold colour-drain wash
var warm: ColorRect                                 # warm tint (golden age / dawn)
var redwash: ColorRect                              # red alarm pulse (fracture)
var debris: CPUParticles2D                          # falling rubble (fracture)
var flash: ColorRect
var fade_overlay: ColorRect
var caption: NinePatchRect
var title_label: Label
var body_label: RichTextLabel
var prompt: Label

var beat: int = -1
var busy: bool = true
var prompt_ready: bool = false
var _t: float = 0.0
var _shake: float = 0.0


# ================================================================= lifecycle =
func _ready() -> void:
	layer = 100
	visible = true
	if custom_font == null:
		var f := load("res://art/Cute_Fantasy_Free2/Outdoor decoration/determination/determination.ttf")
		if f:
			custom_font = f
	_build()
	await get_tree().process_frame
	_start()


func _process(delta: float) -> void:
	_t += delta
	if is_instance_valid(rift):
		rift.rotation += delta * 0.04
	if is_instance_valid(rays):
		rays.rotation -= delta * 0.02
	# screen shake via the CanvasLayer offset
	if _shake > 0.01:
		offset = Vector2(randf_range(-_shake, _shake), randf_range(-_shake, _shake))
		_shake = lerp(_shake, 0.0, clampf(delta * 6.0, 0.0, 1.0))
	elif offset != Vector2.ZERO:
		offset = Vector2.ZERO
	# bob the living emblems (and their halos) in beat 1
	if beat == 0:
		for i in emblem_sprites.size():
			var sp: Sprite2D = emblem_sprites[i]
			if is_instance_valid(sp):
				var ny: float = sp.get_meta("base_y") + sin(_t * 1.5 + i * 0.8) * 6.0
				sp.position.y = ny
				var halo = sp.get_meta("halo")
				if is_instance_valid(halo):
					halo.position.y = ny


# ===================================================================== build =
func _build() -> void:
	var solid := ColorRect.new()
	solid.color = Color("160f30")
	solid.anchor_right = 1.0; solid.anchor_bottom = 1.0
	solid.z_index = -300
	solid.mouse_filter = Control.MOUSE_FILTER_IGNORE
	add_child(solid)

	_parallax("sky", -200)
	_make_rift()
	_parallax("hills", -150)
	_make_clouds()
	_parallax("skyline", -120)
	_parallax("foreground", -90)
	_make_twinkles()
	_make_hero()

	# realm emblems in an arc above the world, each with a domain-tinted halo
	for i in DOMAINS.size():
		var x: float = lerp(366.0, 786.0, i / 4.0)
		var y: float = 196.0 - 26.0 * sin(PI * i / 4.0)
		var ac: Color = ACCENT[DOMAINS[i]]

		var halo := Sprite2D.new()
		halo.texture = _tex("glow")
		halo.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST
		halo.position = Vector2(x, y)
		halo.scale = Vector2(0.85, 0.85)
		halo.modulate = Color(ac.r, ac.g, ac.b, 0.0)
		halo.z_index = -61
		var hm := CanvasItemMaterial.new()
		hm.blend_mode = CanvasItemMaterial.BLEND_MODE_ADD
		halo.material = hm
		add_child(halo)
		emblem_halos.append(halo)

		var sp := Sprite2D.new()
		sp.texture = _tex("emblem_" + DOMAINS[i].to_lower())
		sp.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST
		sp.scale = Vector2(1.3, 1.3)
		sp.position = Vector2(x, y)
		sp.set_meta("base_y", y)
		sp.set_meta("halo", halo)
		sp.modulate.a = 0.0
		sp.z_index = -60
		add_child(sp)
		emblem_sprites.append(sp)

	# warm tint wash (golden age & dawn) — additive
	warm = ColorRect.new()
	warm.color = Color(1.0, 0.6, 0.26)
	warm.anchor_right = 1.0; warm.anchor_bottom = 1.0
	warm.z_index = -44
	warm.mouse_filter = Control.MOUSE_FILTER_IGNORE
	warm.modulate.a = 0.0
	var wmat := CanvasItemMaterial.new()
	wmat.blend_mode = CanvasItemMaterial.BLEND_MODE_ADD
	warm.material = wmat
	add_child(warm)

	# cold dimming wash (the world losing its light)
	dim = ColorRect.new()
	dim.color = Color("0c1020")
	dim.anchor_right = 1.0; dim.anchor_bottom = 1.0
	dim.z_index = -40
	dim.mouse_filter = Control.MOUSE_FILTER_IGNORE
	dim.modulate.a = 0.0
	add_child(dim)

	# red alarm wash for the fracture — additive, pulsed
	redwash = ColorRect.new()
	redwash.color = Color(0.92, 0.16, 0.12)
	redwash.anchor_right = 1.0; redwash.anchor_bottom = 1.0
	redwash.z_index = -36
	redwash.mouse_filter = Control.MOUSE_FILTER_IGNORE
	redwash.modulate.a = 0.0
	var rmat := CanvasItemMaterial.new()
	rmat.blend_mode = CanvasItemMaterial.BLEND_MODE_ADD
	redwash.material = rmat
	add_child(redwash)

	# falling rubble for the fracture (idle until beat 2)
	debris = CPUParticles2D.new()
	debris.texture = _tex("shard")
	debris.position = Vector2(W / 2, -24)
	debris.amount = 46
	debris.lifetime = 2.8
	debris.one_shot = false
	debris.emitting = false
	debris.z_index = -50
	debris.emission_shape = CPUParticles2D.EMISSION_SHAPE_RECTANGLE
	debris.emission_rect_extents = Vector2(W / 2, 8)
	debris.direction = Vector2(0, 1)
	debris.spread = 14.0
	debris.gravity = Vector2(0, 340)
	debris.initial_velocity_min = 40.0
	debris.initial_velocity_max = 130.0
	debris.angular_velocity_min = -280.0
	debris.angular_velocity_max = 280.0
	debris.scale_amount_min = 0.7
	debris.scale_amount_max = 2.0
	add_child(debris)

	# vignette over the scene
	var vig := TextureRect.new()
	vig.texture = _tex("vignette")
	vig.expand_mode = TextureRect.EXPAND_IGNORE_SIZE
	vig.stretch_mode = TextureRect.STRETCH_SCALE
	vig.anchor_right = 1.0; vig.anchor_bottom = 1.0
	vig.mouse_filter = Control.MOUSE_FILTER_IGNORE
	vig.z_index = 30
	add_child(vig)

	# --- caption bar UI (raised + roomy, with a clear bottom margin) ---
	caption = _nine("caption", 14)
	caption.size = Vector2(1004, 192)
	caption.position = Vector2(W / 2 - 502, 396)
	caption.pivot_offset = Vector2(502, 96)
	caption.modulate.a = 0.0
	add_child(caption)

	title_label = _label(40, HORIZONTAL_ALIGNMENT_CENTER)
	title_label.position = Vector2(W / 2 - 470, 408)
	title_label.size = Vector2(940, 44)
	title_label.modulate.a = 0.0
	add_child(title_label)

	body_label = RichTextLabel.new()
	body_label.bbcode_enabled = true
	body_label.scroll_active = false
	body_label.fit_content = false
	body_label.position = Vector2(W / 2 - 456, 454)
	body_label.size = Vector2(912, 122)
	body_label.add_theme_font_size_override("normal_font_size", 24)
	body_label.add_theme_font_size_override("bold_font_size", 24)
	body_label.add_theme_constant_override("line_separation", 5)
	body_label.add_theme_color_override("default_color", Color("f0e6d0"))
	if custom_font:
		body_label.add_theme_font_override("normal_font", custom_font)
		body_label.add_theme_font_override("bold_font", custom_font)
		body_label.add_theme_font_override("italics_font", custom_font)
	body_label.modulate.a = 0.0
	add_child(body_label)

	prompt = _label(20, HORIZONTAL_ALIGNMENT_CENTER)
	prompt.text = "▸  Press SPACE to continue          ESC to skip"
	prompt.position = Vector2(W / 2 - 470, 602)
	prompt.size = Vector2(940, 28)
	prompt.add_theme_color_override("font_color", Color("ffd07a"))
	prompt.modulate.a = 0.0
	add_child(prompt)

	# fade-from-black, on top of everything
	fade_overlay = ColorRect.new()
	fade_overlay.color = Color.BLACK
	fade_overlay.anchor_right = 1.0; fade_overlay.anchor_bottom = 1.0
	fade_overlay.z_index = 1000
	fade_overlay.mouse_filter = Control.MOUSE_FILTER_IGNORE
	add_child(fade_overlay)

	# white flash for the fracture, just under the fade overlay
	flash = ColorRect.new()
	flash.color = Color(1, 1, 1)
	flash.anchor_right = 1.0; flash.anchor_bottom = 1.0
	flash.z_index = 900
	flash.mouse_filter = Control.MOUSE_FILTER_IGNORE
	flash.modulate.a = 0.0
	add_child(flash)


# ----------------------------------------------------------- build helpers ---
func _tex(n: String) -> Texture2D:
	if tex_cache.has(n):
		return tex_cache[n]
	var p := ART + n + ".png"
	var t: Texture2D = load(p) if ResourceLoader.exists(p) else null
	tex_cache[n] = t
	return t


func _parallax(n: String, z: int) -> void:
	var tr := TextureRect.new()
	tr.texture = _tex(n)
	tr.anchor_right = 1.0; tr.anchor_bottom = 1.0
	tr.expand_mode = TextureRect.EXPAND_IGNORE_SIZE
	tr.stretch_mode = TextureRect.STRETCH_SCALE
	tr.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST
	tr.mouse_filter = Control.MOUSE_FILTER_IGNORE
	tr.z_index = z
	add_child(tr)
	parallax_layers.append(tr)


func _label(size: int, align: int) -> Label:
	var l := Label.new()
	l.horizontal_alignment = align
	l.vertical_alignment = VERTICAL_ALIGNMENT_CENTER
	l.mouse_filter = Control.MOUSE_FILTER_IGNORE
	l.add_theme_font_size_override("font_size", size)
	l.add_theme_color_override("font_color", Color("fdeccb"))
	l.add_theme_color_override("font_outline_color", Color(0.05, 0.03, 0.10))
	l.add_theme_constant_override("outline_size", 8)
	l.add_theme_color_override("font_shadow_color", Color(0, 0, 0, 0.55))
	l.add_theme_constant_override("shadow_offset_x", 2)
	l.add_theme_constant_override("shadow_offset_y", 3)
	if custom_font:
		l.add_theme_font_override("font", custom_font)
	return l


func _nine(name: String, margin: int) -> NinePatchRect:
	var n := NinePatchRect.new()
	n.texture = _tex(name)
	n.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST
	n.patch_margin_left = margin
	n.patch_margin_top = margin
	n.patch_margin_right = margin
	n.patch_margin_bottom = margin
	return n


func _make_rift() -> void:
	rays = Sprite2D.new()
	rays.texture = _tex("rays")
	if rays.texture:
		rays.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST
		rays.position = RIFT
		rays.scale = Vector2(3.0, 3.0)
		rays.modulate = Color(1, 1, 1, 0.5)
		rays.z_index = -175
		var mr := CanvasItemMaterial.new()
		mr.blend_mode = CanvasItemMaterial.BLEND_MODE_ADD
		rays.material = mr
		add_child(rays)
	# warm sun bloom behind the rift (golden age & dawn)
	sun = Sprite2D.new()
	sun.texture = _tex("glow")
	if sun.texture:
		sun.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST
		sun.position = RIFT
		sun.scale = Vector2(7.0, 7.0)
		sun.modulate = Color(1.0, 0.82, 0.42, 0.0)
		sun.z_index = -180
		var ms := CanvasItemMaterial.new()
		ms.blend_mode = CanvasItemMaterial.BLEND_MODE_ADD
		sun.material = ms
		add_child(sun)

	rift = Sprite2D.new()
	rift.texture = _tex("vortex")
	if rift.texture:
		rift.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST
		rift.position = RIFT
		rift.scale = Vector2(2.6, 2.6)
		rift.modulate = Color(1, 1, 1, 0.0)
		rift.z_index = -170
		var mv := CanvasItemMaterial.new()
		mv.blend_mode = CanvasItemMaterial.BLEND_MODE_ADD
		rift.material = mv
		add_child(rift)


func _make_clouds() -> void:
	var clouds := TextureRect.new()
	clouds.texture = _tex("clouds")
	clouds.expand_mode = TextureRect.EXPAND_IGNORE_SIZE
	clouds.stretch_mode = TextureRect.STRETCH_SCALE
	clouds.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST
	clouds.mouse_filter = Control.MOUSE_FILTER_IGNORE
	clouds.size = Vector2(1536, 330)
	clouds.position = Vector2(-320, 16)
	clouds.z_index = -140
	clouds.modulate.a = 0.8
	add_child(clouds)
	var t := create_tween().set_loops()
	t.tween_property(clouds, "position:x", -150, 72.0).set_trans(Tween.TRANS_SINE).set_ease(Tween.EASE_IN_OUT)
	t.tween_property(clouds, "position:x", -320, 72.0).set_trans(Tween.TRANS_SINE).set_ease(Tween.EASE_IN_OUT)


func _make_twinkles() -> void:
	var spark := _tex("sparkle")
	if spark == null:
		return
	var rng := RandomNumberGenerator.new()
	rng.seed = 14
	for i in 16:
		var s := Sprite2D.new()
		s.texture = spark
		s.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST
		s.position = Vector2(rng.randf_range(30, W - 30), rng.randf_range(24, 280))
		s.scale = Vector2.ONE * rng.randf_range(0.6, 1.4)
		s.modulate = Color(1, 1, 1, rng.randf_range(0.2, 0.6))
		s.z_index = -160
		var m := CanvasItemMaterial.new()
		m.blend_mode = CanvasItemMaterial.BLEND_MODE_ADD
		s.material = m
		add_child(s)
		var t := create_tween().set_loops()
		var dur := rng.randf_range(1.0, 2.4)
		t.tween_property(s, "modulate:a", 0.85, dur).set_trans(Tween.TRANS_SINE)
		t.tween_property(s, "modulate:a", 0.1, dur).set_trans(Tween.TRANS_SINE)


func _make_hero() -> void:
	hero = Sprite2D.new()
	hero.texture = _tex("hero")
	if hero.texture == null:
		return
	hero.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST
	hero.scale = Vector2(3.4, 3.4)
	hero.position = Vector2(W / 2, H - 60)
	hero.modulate.a = 0.0
	hero.z_index = -80
	add_child(hero)

	# a cool light around the Shifter's staff orb (hero-local; blooms in beat 3)
	staff_glow = Sprite2D.new()
	staff_glow.texture = _tex("glow")
	if staff_glow.texture:
		staff_glow.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST
		staff_glow.position = Vector2(8, -19)           # the staff orb in hero-local space
		staff_glow.scale = Vector2(0.42, 0.42)
		staff_glow.modulate = Color(0.72, 0.86, 1.0, 0.0)
		var sgm := CanvasItemMaterial.new()
		sgm.blend_mode = CanvasItemMaterial.BLEND_MODE_ADD
		staff_glow.material = sgm
		hero.add_child(staff_glow)


# ================================================================ sequencing =
func _start() -> void:
	var t := create_tween()
	t.tween_property(fade_overlay, "modulate:a", 0.0, 1.6).set_ease(Tween.EASE_IN_OUT)
	if is_instance_valid(rift):
		t.parallel().tween_property(rift, "modulate:a", 0.95, 1.8)
	await t.finished
	_beat_golden()


func _set_caption(b: Dictionary) -> void:
	title_label.text = b.title
	title_label.add_theme_color_override("font_color", Color(b.color))
	body_label.text = b.text
	# wait one frame so the RichTextLabel reflows, then centre the title+body
	# block in the bar — short (2-line) and long (3-line) beats both stay balanced
	# instead of hugging the top with a slab of dead space underneath.
	await get_tree().process_frame
	_layout_caption()
	var t := create_tween().set_parallel(true)
	t.tween_property(caption, "modulate:a", 1.0, 0.5)
	t.tween_property(title_label, "modulate:a", 1.0, 0.6)
	t.tween_property(body_label, "modulate:a", 1.0, 0.7)
	caption.scale = Vector2(0.97, 0.94)
	t.tween_property(caption, "scale", Vector2.ONE, 0.5).set_trans(Tween.TRANS_BACK).set_ease(Tween.EASE_OUT)


# Vertically centre the title + body block inside the caption bar so the text is
# evenly spaced top and bottom regardless of how many lines the body wraps to.
func _layout_caption() -> void:
	var title_h := title_label.get_combined_minimum_size().y
	var body_h := body_label.get_content_height()
	var gap := 8.0
	var block := title_h + gap + body_h
	# usable band between the caption's top and bottom gold rules
	var top := caption.position.y + 26.0
	var bottom := caption.position.y + caption.size.y - 24.0
	var start := top + maxf(0.0, ((bottom - top) - block) * 0.5)
	title_label.position.y = start
	title_label.size.y = title_h
	body_label.position.y = start + title_h + gap
	body_label.size.y = maxf(body_h, 40.0)


func _clear_caption() -> void:
	var t := create_tween().set_parallel(true)
	t.tween_property(caption, "modulate:a", 0.0, 0.35)
	t.tween_property(title_label, "modulate:a", 0.0, 0.35)
	t.tween_property(body_label, "modulate:a", 0.0, 0.35)
	t.tween_property(prompt, "modulate:a", 0.0, 0.3)
	await t.finished


# --------------------------------------------------- BEAT 1: the golden age --
func _beat_golden() -> void:
	beat = 0
	busy = true
	_set_caption(BEATS[0])
	# a golden light fills the sky and warms the rift
	create_tween().tween_property(sun, "modulate", Color(1.0, 0.82, 0.42, 0.62), 1.4)
	create_tween().tween_property(warm, "modulate:a", 0.14, 1.4)
	if is_instance_valid(rift):
		create_tween().tween_property(rift, "modulate", Color(1.3, 1.15, 0.92, 0.98), 1.4)
	# the five realms light up one by one, haloes blooming
	for i in emblem_sprites.size():
		var sp: Sprite2D = emblem_sprites[i]
		sp.scale = Vector2(0.2, 0.2)
		sp.modulate = Color(1, 1, 1, 0)
		var et := create_tween().set_parallel(true)
		et.tween_property(sp, "modulate:a", 1.0, 0.3)
		et.tween_property(sp, "scale", Vector2(1.3, 1.3), 0.5) \
			.set_trans(Tween.TRANS_BACK).set_ease(Tween.EASE_OUT)
		var halo = sp.get_meta("halo")
		if is_instance_valid(halo):
			create_tween().tween_property(halo, "modulate:a", 0.7, 0.5)
		_pop(sp.position, ACCENT[DOMAINS[i]])
		await get_tree().create_timer(0.16).timeout
	await get_tree().create_timer(0.2).timeout
	await _show_prompt()


# ------------------------------------------------------- BEAT 2: the fracture =
func _beat_fracture() -> void:
	beat = 1
	busy = true

	# the golden light dies in an instant
	create_tween().tween_property(sun, "modulate:a", 0.0, 0.2)
	create_tween().tween_property(warm, "modulate:a", 0.0, 0.2)

	# blinding white flash + violent shake
	flash.modulate.a = 0.0
	var ft := create_tween()
	ft.tween_property(flash, "modulate:a", 1.0, 0.05)
	ft.tween_property(flash, "modulate:a", 0.0, 0.55)
	_shake = 30.0

	# a main bolt tears down the sky, with two forks to either side
	_bolt(Vector2(W / 2, 198), 3.4, 0.0)
	_bolt(Vector2(W * 0.30, 150), 2.3, -0.35)
	_bolt(Vector2(W * 0.70, 168), 2.7, 0.40)

	# rubble rains down for a moment
	if is_instance_valid(debris):
		debris.emitting = true
		get_tree().create_timer(1.7).timeout.connect(func():
			if is_instance_valid(debris):
				debris.emitting = false)

	# red alarm light pulses across the world
	var aw := create_tween()
	aw.tween_property(redwash, "modulate:a", 0.5, 0.1)
	aw.tween_property(redwash, "modulate:a", 0.12, 0.4)
	aw.tween_property(redwash, "modulate:a", 0.42, 0.22)
	aw.tween_property(redwash, "modulate:a", 0.16, 0.7)

	# the rift overloads, flares white, then collapses to a sickly red
	if is_instance_valid(rift):
		var rt := create_tween()
		rt.tween_property(rift, "modulate", Color(2.1, 2.1, 2.3, 1.0), 0.16)
		rt.parallel().tween_property(rift, "scale", Vector2(3.0, 3.0), 0.16)
		rt.tween_property(rift, "modulate", Color(1.35, 0.4, 0.42, 0.42), 0.7)
		rt.parallel().tween_property(rift, "scale", Vector2(2.15, 2.15), 0.7)
	await get_tree().create_timer(0.22).timeout

	# the world drains to cold grey; the realms shatter and tumble dark
	var dt := create_tween()
	dt.tween_property(dim, "modulate:a", 0.72, 1.2)
	var rng := RandomNumberGenerator.new(); rng.seed = 3
	for i in emblem_sprites.size():
		var sp: Sprite2D = emblem_sprites[i]
		var halo = sp.get_meta("halo")
		if is_instance_valid(halo):
			create_tween().tween_property(halo, "modulate:a", 0.0, 0.4)
		_pop(sp.position, Color(0.55, 0.55, 0.66), 10)        # a dull shatter puff
		var gt := create_tween().set_parallel(true)
		gt.tween_property(sp, "modulate", Color(0.3, 0.3, 0.38, 0.8), 0.9)
		gt.tween_property(sp, "position:y", sp.get_meta("base_y") + rng.randf_range(46, 96), 1.1) \
			.set_trans(Tween.TRANS_CUBIC).set_ease(Tween.EASE_IN)
		gt.tween_property(sp, "position:x", sp.position.x + rng.randf_range(-44, 44), 1.1)
		gt.tween_property(sp, "rotation", rng.randf_range(-1.1, 1.1), 1.1)
	_shake = maxf(_shake, 16.0)                                # an aftershock as they fall
	await get_tree().create_timer(1.0).timeout

	_clear_caption_quick()
	_set_caption(BEATS[1])
	await get_tree().create_timer(0.3).timeout
	await _show_prompt()


# spawn a single additive lightning bolt that flashes in then fades away
func _bolt(pos: Vector2, scl: float, rot: float) -> void:
	var b := Sprite2D.new()
	b.texture = _tex("crack")
	if b.texture == null:
		return
	b.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST
	b.position = pos
	b.rotation = rot
	b.scale = Vector2(scl * 0.8, scl * 0.8)
	b.modulate = Color(1, 1, 1, 0)
	b.z_index = -55
	var m := CanvasItemMaterial.new()
	m.blend_mode = CanvasItemMaterial.BLEND_MODE_ADD
	b.material = m
	add_child(b)
	var t := create_tween()
	t.tween_property(b, "modulate:a", 1.0, 0.06)
	t.parallel().tween_property(b, "scale", Vector2(scl, scl), 0.5).set_trans(Tween.TRANS_BACK)
	t.tween_property(b, "modulate:a", 0.0, 0.7)
	t.tween_callback(b.queue_free)


# ---------------------------------------------------- BEAT 3: the last shifter =
func _beat_shifter() -> void:
	beat = 2
	busy = true

	# the alarm dies; a gentle dawn rises over the horizon
	create_tween().tween_property(redwash, "modulate:a", 0.0, 1.0)
	var wt := create_tween()
	wt.tween_property(dim, "modulate:a", 0.22, 1.4)
	wt.parallel().tween_property(dim, "color", Color("241a32"), 1.4)
	create_tween().tween_property(warm, "modulate:a", 0.08, 1.6)
	if is_instance_valid(sun):
		sun.position = Vector2(W / 2, H - 150)                # low, on the horizon
		sun.scale = Vector2(9.0, 5.2)
		create_tween().tween_property(sun, "modulate", Color(1.0, 0.72, 0.44, 0.42), 1.6)
	if is_instance_valid(rift):
		create_tween().tween_property(rift, "modulate", Color(0.82, 0.92, 1.0, 0.7), 1.6)
		create_tween().tween_property(rift, "scale", Vector2(2.5, 2.5), 1.6)

	# the Shifter rises on the hill, staff aglow
	if is_instance_valid(hero):
		hero.position = Vector2(W / 2, H - 30)
		var ht := create_tween().set_parallel(true)
		ht.tween_property(hero, "modulate:a", 1.0, 0.9)
		ht.tween_property(hero, "position:y", H - 60, 0.9).set_trans(Tween.TRANS_BACK).set_ease(Tween.EASE_OUT)
		if is_instance_valid(staff_glow):
			ht.tween_property(staff_glow, "modulate:a", 0.95, 1.3)
		await ht.finished
		var bob := create_tween().set_loops()
		bob.tween_property(hero, "position:y", H - 68, 1.5).set_trans(Tween.TRANS_SINE)
		bob.tween_property(hero, "position:y", H - 60, 1.5).set_trans(Tween.TRANS_SINE)
		if is_instance_valid(staff_glow):
			var sb := create_tween().set_loops()
			sb.tween_property(staff_glow, "scale", Vector2(0.52, 0.52), 1.4).set_trans(Tween.TRANS_SINE)
			sb.tween_property(staff_glow, "scale", Vector2(0.42, 0.42), 1.4).set_trans(Tween.TRANS_SINE)

	# the realms right themselves and half-relight — waiting to be reclaimed
	for i in emblem_sprites.size():
		var sp: Sprite2D = emblem_sprites[i]
		var ac: Color = ACCENT[DOMAINS[i]]
		var rt := create_tween().set_parallel(true)
		rt.tween_property(sp, "modulate", Color(0.72, 0.72, 0.78, 0.92), 0.7)
		rt.tween_property(sp, "rotation", 0.0, 0.7).set_trans(Tween.TRANS_SINE)
		rt.tween_property(sp, "position:y", sp.get_meta("base_y") + 24.0, 0.7).set_trans(Tween.TRANS_SINE)
		var halo = sp.get_meta("halo")
		if is_instance_valid(halo):
			halo.position = Vector2(sp.position.x, sp.get_meta("base_y") + 24.0)
			create_tween().tween_property(halo, "modulate:a", 0.3, 0.7)
		_pop(sp.position, ac, 8)
		await get_tree().create_timer(0.08).timeout

	_clear_caption_quick()
	_set_caption(BEATS[2])
	await get_tree().create_timer(0.3).timeout
	await _show_prompt("▸  Press SPACE to begin")


func _clear_caption_quick() -> void:
	caption.modulate.a = 0.0
	title_label.modulate.a = 0.0
	body_label.modulate.a = 0.0
	prompt.modulate.a = 0.0


# ----------------------------------------------------------------- particles -
func _pop(pos: Vector2, col: Color, amount: int = 16) -> void:
	var p := CPUParticles2D.new()
	p.texture = _tex("sparkle")
	p.position = pos
	p.one_shot = true
	p.explosiveness = 1.0
	p.amount = amount
	p.lifetime = 0.8
	p.z_index = -50
	p.direction = Vector2(0, -1)
	p.spread = 180.0
	p.initial_velocity_min = 40.0
	p.initial_velocity_max = 150.0
	p.scale_amount_min = 1.0
	p.scale_amount_max = 2.4
	var g := Gradient.new()
	g.set_color(0, Color(col.r, col.g, col.b, 1.0))
	g.set_color(1, Color(col.r, col.g, col.b, 0.0))
	p.color_ramp = g
	var m := CanvasItemMaterial.new()
	m.blend_mode = CanvasItemMaterial.BLEND_MODE_ADD
	p.material = m
	p.emitting = true
	add_child(p)
	get_tree().create_timer(1.4).timeout.connect(func():
		if is_instance_valid(p):
			p.queue_free())


func _show_prompt(text: String = "▸  Press SPACE to continue          ESC to skip") -> void:
	prompt.text = text
	var t := create_tween()
	t.tween_property(prompt, "modulate:a", 0.9, 0.5)
	await t.finished
	var p := create_tween().set_loops()
	p.tween_property(prompt, "modulate:a", 0.4, 0.9).set_trans(Tween.TRANS_SINE)
	p.tween_property(prompt, "modulate:a", 0.95, 0.9).set_trans(Tween.TRANS_SINE)
	busy = false
	prompt_ready = true


# ===================================================================== input =
func _input(event: InputEvent) -> void:
	if event.is_action_pressed("ui_cancel"):
		_go_to_hub()
		return
	if event.is_action_pressed("ui_accept") and prompt_ready and not busy:
		_advance()


func _advance() -> void:
	prompt_ready = false
	busy = true
	match beat:
		0:
			await _clear_caption()
			_beat_fracture()
		1:
			_beat_shifter()
		2:
			_go_to_hub()


func _go_to_hub() -> void:
	if beat == -2:                                  # already leaving
		return
	beat = -2
	prompt_ready = false
	fade_overlay.z_index = 2000
	var t := create_tween()
	t.tween_property(fade_overlay, "modulate:a", 1.0, 1.4).set_ease(Tween.EASE_IN)
	await t.finished
	global.show_hub_tutorial = true
	get_tree().change_scene_to_file("res://scenes/maps/MainHub.tscn")
