# TitleScreen.gd
# A dynamic, animated, pixel-art main menu for "CAREER REALMS - The Shifter's Path".
#
# A parallax cosmic-dusk panorama (sky, hills, drifting clouds, a distant
# fantasy skyline, a hilltop foreground) carries an animated RIFT centrepiece
# (a slowly rotating five-armed portal + counter-rotating god-rays), twinkling
# stars, rising embers and birds. Over it: the bold CAREER REALMS logo on an
# ornate banner, the five realm emblems bobbing in an arc, and pixel-art menu
# buttons (New Game / Controls / Credits / Exit) driven by BOTH mouse and
# keyboard with a hover/selection glow. Subtle mouse parallax makes it breathe.
#
# All art is generated by tools/make_title.py into assets/generated/title/.
# Attach to the CanvasLayer root of the title scene.

extends CanvasLayer

@export var custom_font: Font

const ART := "res://assets/generated/title/"
const W := 1152.0
const H := 648.0
const RIFT := Vector2(576, 250)                 # rift centre on screen

# title_banner.png geometry (keep in sync with tools/make_title.py make_title_banner):
# native size + the open dark inner panel where text is laid out, in native px.
const BANNER_NATIVE := Vector2(392, 96)
const BANNER_INNER := Rect2(41, 14, 310, 68)
const DOMAINS := ["Engineering", "Farming", "Leadership", "Medicine", "Art"]
const ACCENT := {
	"Engineering": Color("f4c12e"), "Farming": Color("5fc85a"),
	"Leadership": Color("3f8cf0"), "Medicine": Color("a25bf0"), "Art": Color("e8554e"),
}

# menu entries: label + handler method name + domain accent colour
const ENTRIES := [
	{"label": "New Game", "fn": "_on_new_game", "color": "f4c12e"},
	{"label": "Controls", "fn": "_on_controls", "color": "5fc85a"},
	{"label": "Credits", "fn": "_on_credits", "color": "3f8cf0"},
	{"label": "Exit", "fn": "_on_exit", "color": "e8554e"},
]

const IMPORTANT_CONTROLS := [
	{"label": "Move", "keys": "W A S D / Arrows"},
	{"label": "Interact / Talk", "action": "talk", "fallback": "Tab"},
	{"label": "Inventory", "action": "i", "fallback": "I"},
	{"label": "View Stats", "action": "craft", "fallback": "R"},
	{"label": "Confirm", "action": "ui_accept", "fallback": "Enter / Space"},
	{"label": "Back / Pause", "action": "ui_cancel", "fallback": "Esc"},
]

# nodes / state
var tex_cache: Dictionary = {}
var parallax_layers: Array = []                 # [{node, factor, base}]
var rift: Sprite2D
var rays: Sprite2D
var hero: Sprite2D
var emblem_sprites: Array = []
var content: Control
var title_label: Label
var title_glow: Label
var subtitle_label: Label
var buttons: Array = []                         # [{root, frame, hi, label, arrow, fn}]
var selected: int = 0
var ready_for_input: bool = false
var fade_overlay: ColorRect

# info overlay (Controls / About)
var info_root: Control
var info_dim: ColorRect
var info_panel: NinePatchRect
var info_header: TextureRect
var info_title: Label
var info_content: Control
var info_hint: Label
var info_open: bool = false

var _t: float = 0.0
var _mouse_norm: Vector2 = Vector2.ZERO


# ================================================================= lifecycle =
func _ready() -> void:
	layer = 50
	visible = true
	if custom_font == null:
		var f := load("res://art/Cute_Fantasy_Free2/Outdoor decoration/determination/determination.ttf")
		if f:
			custom_font = f
	_build()
	await get_tree().process_frame
	_intro_animation()


func _process(delta: float) -> void:
	_t += delta
	if is_instance_valid(rift):
		rift.rotation += delta * 0.03
	if is_instance_valid(rays):
		rays.rotation -= delta * 0.018

	# smooth mouse parallax + gentle idle sway
	var mp := get_viewport().get_mouse_position()
	var target := Vector2((mp.x / W) - 0.5, (mp.y / H) - 0.5) * 2.0
	_mouse_norm = _mouse_norm.lerp(target, clampf(delta * 3.0, 0.0, 1.0))
	var sway := Vector2(sin(_t * 0.25), cos(_t * 0.19)) * 0.12
	var off := _mouse_norm + sway
	for L in parallax_layers:
		if is_instance_valid(L.node):
			L.node.position = L.base + off * L.factor

	# bob the realm emblems (and their halos) in their arc
	for i in emblem_sprites.size():
		var sp: Sprite2D = emblem_sprites[i]
		if is_instance_valid(sp):
			var ny: float = sp.get_meta("base_y") + sin(_t * 1.4 + i * 0.9) * 7.0
			sp.position.y = ny
			var halo = sp.get_meta("halo")
			if is_instance_valid(halo):
				halo.position.y = ny


# ===================================================================== build =
func _build() -> void:
	# never-black backstop
	var solid := ColorRect.new()
	solid.color = Color("160f30")
	solid.anchor_right = 1.0; solid.anchor_bottom = 1.0
	solid.z_index = -300
	solid.mouse_filter = Control.MOUSE_FILTER_IGNORE
	add_child(solid)

	_parallax("sky", -200, 14.0)
	_make_rift()
	_parallax("hills", -150, 26.0)
	_make_clouds()
	_parallax("skyline", -120, 40.0)
	_parallax("foreground", -90, 64.0)
	_make_twinkles()
	_make_embers()
	_make_birds()
	_make_hero()

	# --- content overlay ---
	content = Control.new()
	content.anchor_right = 1.0; content.anchor_bottom = 1.0
	content.mouse_filter = Control.MOUSE_FILTER_IGNORE
	content.z_index = 10
	add_child(content)

	# ornate title plate: banner + CAREER REALMS + THE SHIFTER'S PATH, all inside
	_build_title_plate()

	# the five realm emblems, in a gentle arc in their own band below the banner
	for i in DOMAINS.size():
		var x: float = lerp(416.0, 736.0, i / 4.0)
		var y: float = 258.0 - 12.0 * sin(PI * i / 4.0)
		# soft domain-tinted halo behind each emblem (reads as a glowing crest)
		var halo := Sprite2D.new()
		halo.texture = _tex("glow")
		halo.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST
		halo.position = Vector2(x, y)
		halo.scale = Vector2(0.6, 0.6)
		var ac: Color = ACCENT[DOMAINS[i]]
		halo.modulate = Color(ac.r, ac.g, ac.b, 0.0)
		halo.z_index = 10
		var hm := CanvasItemMaterial.new()
		hm.blend_mode = CanvasItemMaterial.BLEND_MODE_ADD
		halo.material = hm
		content.add_child(halo)

		var sp := Sprite2D.new()
		sp.texture = _tex("emblem_" + DOMAINS[i].to_lower())
		sp.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST
		sp.scale = Vector2(0.95, 0.95)
		sp.position = Vector2(x, y)
		sp.set_meta("base_y", y)
		sp.set_meta("halo", halo)
		sp.modulate.a = 0.0
		sp.z_index = 11
		content.add_child(sp)
		emblem_sprites.append(sp)

	_build_buttons()

	# bottom hints
	var nav := _label(20, HORIZONTAL_ALIGNMENT_CENTER)
	nav.text = "↑ ↓  Select          ENTER  Confirm"
	nav.anchor_left = 0.0; nav.anchor_right = 1.0
	nav.offset_top = 592; nav.offset_bottom = 620
	nav.add_theme_color_override("font_color", Color("cdbfe6"))
	nav.modulate.a = 0.0
	nav.name = "NavHint"
	content.add_child(nav)

	var ver := _label(18, HORIZONTAL_ALIGNMENT_RIGHT)
	ver.text = "v1.0"
	ver.anchor_left = 0.0; ver.anchor_right = 1.0
	ver.offset_right = -18
	ver.offset_top = 612; ver.offset_bottom = 640
	ver.add_theme_color_override("font_color", Color(0.7, 0.66, 0.85, 0.7))
	content.add_child(ver)

	# vignette
	var vig := TextureRect.new()
	vig.texture = _tex("vignette")
	vig.expand_mode = TextureRect.EXPAND_IGNORE_SIZE
	vig.stretch_mode = TextureRect.STRETCH_SCALE
	vig.anchor_right = 1.0; vig.anchor_bottom = 1.0
	vig.mouse_filter = Control.MOUSE_FILTER_IGNORE
	vig.z_index = 60
	add_child(vig)

	_build_info_overlay()

	# fade-from-black
	fade_overlay = ColorRect.new()
	fade_overlay.color = Color.BLACK
	fade_overlay.anchor_right = 1.0; fade_overlay.anchor_bottom = 1.0
	fade_overlay.z_index = 200
	fade_overlay.mouse_filter = Control.MOUSE_FILTER_IGNORE
	add_child(fade_overlay)


# ----------------------------------------------------------- build helpers ---
func _tex(n: String) -> Texture2D:
	if tex_cache.has(n):
		return tex_cache[n]
	var p := ART + n + ".png"
	var t: Texture2D = load(p) if ResourceLoader.exists(p) else null
	tex_cache[n] = t
	return t


func _parallax(n: String, z: int, factor: float) -> void:
	var tr := TextureRect.new()
	tr.texture = _tex(n)
	# oversize so parallax shifting never reveals an edge
	tr.anchor_right = 1.0; tr.anchor_bottom = 1.0
	tr.offset_left = -90; tr.offset_top = -90
	tr.offset_right = 90; tr.offset_bottom = 90
	tr.expand_mode = TextureRect.EXPAND_IGNORE_SIZE
	tr.stretch_mode = TextureRect.STRETCH_SCALE
	tr.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST
	tr.mouse_filter = Control.MOUSE_FILTER_IGNORE
	tr.z_index = z
	add_child(tr)
	parallax_layers.append({"node": tr, "factor": factor, "base": Vector2.ZERO})


func _label(size: int, align: int) -> Label:
	var l := Label.new()
	l.horizontal_alignment = align
	l.vertical_alignment = VERTICAL_ALIGNMENT_CENTER
	l.mouse_filter = Control.MOUSE_FILTER_IGNORE
	l.add_theme_font_size_override("font_size", size)
	l.add_theme_color_override("font_color", Color("fdeccb"))
	l.add_theme_color_override("font_outline_color", Color(0.05, 0.03, 0.10))
	l.add_theme_constant_override("outline_size", 8)
	l.add_theme_color_override("font_shadow_color", Color(0, 0, 0, 0.55))
	l.add_theme_constant_override("shadow_offset_x", 2)
	l.add_theme_constant_override("shadow_offset_y", 3)
	if custom_font:
		l.add_theme_font_override("font", custom_font)
	return l


# Size + place an ornate banner so it fills its box exactly (no letterboxing),
# which keeps _banner_inner() math exact.
func _place_banner(node: Control, w: float, x: float, y: float) -> void:
	node.expand_mode = TextureRect.EXPAND_IGNORE_SIZE
	node.stretch_mode = TextureRect.STRETCH_SCALE
	node.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST
	node.mouse_filter = Control.MOUSE_FILTER_IGNORE
	node.size = Vector2(w, w * BANNER_NATIVE.y / BANNER_NATIVE.x)
	node.position = Vector2(x, y)


# The banner's open dark inner panel, in screen coordinates — where text goes.
func _banner_inner(node: Control) -> Rect2:
	var s := node.size.x / BANNER_NATIVE.x
	return Rect2(node.position.x + BANNER_INNER.position.x * s,
		node.position.y + BANNER_INNER.position.y * s,
		BANNER_INNER.size.x * s, BANNER_INNER.size.y * s)


# Shrink a label's font until its OWN rendered box fits within (max_w, max_h).
# We measure get_combined_minimum_size() — the box Godot actually lays the label
# out at — instead of Font.get_string_size(): with this pixel font the label's
# real box is much wider than get_string_size reports, and that hidden slack was
# letting the box grow past the banner and shove the centred text off to one side.
func _fit_font(l: Label, start: int, floor_size: int, max_w: float, max_h: float) -> int:
	var fs := start
	while fs > floor_size:
		l.add_theme_font_size_override("font_size", fs)
		var sz := l.get_combined_minimum_size()
		if sz.x <= max_w and sz.y <= max_h:
			break
		fs -= 1
	l.add_theme_font_size_override("font_size", fs)
	return fs


# The title lockup: CAREER REALMS + THE SHIFTER'S PATH stacked INSIDE the banner's
# open centre, both auto-fitted so they keep clear margins on every edge.
func _build_title_plate() -> void:
	var bw := 700.0
	var banner := TextureRect.new()
	banner.name = "Banner"
	banner.texture = _tex("title_banner")
	_place_banner(banner, bw, (W - bw) / 2.0, 22.0)
	banner.pivot_offset = banner.size / 2.0
	banner.modulate.a = 0.0
	content.add_child(banner)

	var ir := _banner_inner(banner)
	var pad_x := 24.0
	var pad_y := 10.0
	var tw := ir.size.x - 2.0 * pad_x
	var usable_h := ir.size.y - 2.0 * pad_y
	var cx := ir.position.x + ir.size.x * 0.5

	# CAREER REALMS — crisp gold copy. Auto-fit it to the panel FIRST so we know
	# the final font size before anything else is sized to match.
	title_label = _label(80, HORIZONTAL_ALIGNMENT_CENTER)
	title_label.text = "CAREER REALMS"
	title_label.add_theme_color_override("font_color", Color("ffd86a"))
	title_label.add_theme_color_override("font_outline_color", Color("2a1708"))
	title_label.add_theme_constant_override("outline_size", 10)
	title_label.modulate.a = 0.0
	content.add_child(title_label)
	var tfs := _fit_font(title_label, 82, 32, tw, usable_h * 0.78)

	# Additive glow copy, BORN at the fitted size (never font 80) so its minimum
	# box matches the crisp copy's exactly. (A Label created large then shrunk
	# keeps the large box cached, which is what used to leave an offset ghost.)
	title_glow = _label(tfs, HORIZONTAL_ALIGNMENT_CENTER)
	title_glow.text = "CAREER REALMS"
	title_glow.add_theme_color_override("font_color", Color(1.0, 0.78, 0.30, 0.55))
	title_glow.add_theme_constant_override("outline_size", 0)
	var glow_mat := CanvasItemMaterial.new()
	glow_mat.blend_mode = CanvasItemMaterial.BLEND_MODE_ADD
	title_glow.material = glow_mat
	title_glow.modulate.a = 0.0
	content.add_child(title_glow)
	content.move_child(title_glow, title_label.get_index())   # draw it behind the crisp copy

	subtitle_label = _label(30, HORIZONTAL_ALIGNMENT_CENTER)
	subtitle_label.text = "T H E   S H I F T E R ' S   P A T H"
	subtitle_label.add_theme_color_override("font_color", Color("ffe6b0"))
	subtitle_label.add_theme_constant_override("outline_size", 6)
	subtitle_label.modulate.a = 0.0
	content.add_child(subtitle_label)
	_fit_font(subtitle_label, 30, 12, tw, usable_h * 0.30)

	# Place each line by its OWN measured box, centred on the banner, then stack
	# the two centred in the open panel. Both title copies use the crisp copy's
	# box so they line up pixel-for-pixel.
	var tmin := title_label.get_combined_minimum_size()
	var smin := subtitle_label.get_combined_minimum_size()
	var gap := 2.0
	var stack_top := ir.position.y + (ir.size.y - (tmin.y + gap + smin.y)) * 0.5
	for l in [title_glow, title_label]:
		l.size = tmin
		l.position = Vector2(cx - tmin.x * 0.5, stack_top)
		l.pivot_offset = tmin * 0.5
	subtitle_label.size = smin
	subtitle_label.position = Vector2(cx - smin.x * 0.5, stack_top + tmin.y + gap)


func _make_rift() -> void:
	rays = Sprite2D.new()
	rays.texture = _tex("rays")
	if rays.texture:
		rays.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST
		rays.position = RIFT
		rays.scale = Vector2(3.0, 3.0)
		rays.modulate = Color(1, 1, 1, 0.5)
		rays.z_index = -175
		var mr := CanvasItemMaterial.new()
		mr.blend_mode = CanvasItemMaterial.BLEND_MODE_ADD
		rays.material = mr
		add_child(rays)

	rift = Sprite2D.new()
	rift.texture = _tex("vortex")
	if rift.texture:
		rift.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST
		rift.position = RIFT
		rift.scale = Vector2(2.5, 2.5)
		rift.modulate = Color(1, 1, 1, 0.0)
		rift.z_index = -170
		var mv := CanvasItemMaterial.new()
		mv.blend_mode = CanvasItemMaterial.BLEND_MODE_ADD
		rift.material = mv
		add_child(rift)
		# slow breathing pulse
		var t := create_tween().set_loops()
		t.tween_property(rift, "scale", Vector2(2.62, 2.62), 3.4).set_trans(Tween.TRANS_SINE)
		t.tween_property(rift, "scale", Vector2(2.5, 2.5), 3.4).set_trans(Tween.TRANS_SINE)


func _make_clouds() -> void:
	var clouds := TextureRect.new()
	clouds.texture = _tex("clouds")
	clouds.expand_mode = TextureRect.EXPAND_IGNORE_SIZE
	clouds.stretch_mode = TextureRect.STRETCH_SCALE
	clouds.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST
	clouds.mouse_filter = Control.MOUSE_FILTER_IGNORE
	clouds.size = Vector2(1536, 330)
	clouds.position = Vector2(-320, 20)
	clouds.z_index = -140
	clouds.modulate.a = 0.85
	add_child(clouds)
	var t := create_tween().set_loops()
	t.tween_property(clouds, "position:x", -120, 70.0).set_trans(Tween.TRANS_SINE).set_ease(Tween.EASE_IN_OUT)
	t.tween_property(clouds, "position:x", -320, 70.0).set_trans(Tween.TRANS_SINE).set_ease(Tween.EASE_IN_OUT)


func _make_twinkles() -> void:
	var spark := _tex("sparkle")
	if spark == null:
		return
	var rng := RandomNumberGenerator.new()
	rng.seed = 24
	for i in 22:
		var s := Sprite2D.new()
		s.texture = spark
		s.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST
		s.position = Vector2(rng.randf_range(30, W - 30), rng.randf_range(24, 300))
		s.scale = Vector2.ONE * rng.randf_range(0.6, 1.5)
		s.modulate = Color(1, 1, 1, rng.randf_range(0.2, 0.6))
		s.z_index = -160
		var m := CanvasItemMaterial.new()
		m.blend_mode = CanvasItemMaterial.BLEND_MODE_ADD
		s.material = m
		add_child(s)
		var t := create_tween().set_loops()
		var dur := rng.randf_range(1.0, 2.4)
		t.tween_property(s, "modulate:a", 0.9, dur).set_trans(Tween.TRANS_SINE)
		t.tween_property(s, "modulate:a", 0.1, dur).set_trans(Tween.TRANS_SINE)


func _make_embers() -> void:
	var p := CPUParticles2D.new()
	p.texture = _tex("sparkle")
	p.position = Vector2(W / 2, H + 10)
	p.amount = 30
	p.lifetime = 8.0
	p.preprocess = 4.0
	p.z_index = -70
	p.emission_shape = CPUParticles2D.EMISSION_SHAPE_RECTANGLE
	p.emission_rect_extents = Vector2(W / 2, 12)
	p.direction = Vector2(0, -1)
	p.spread = 18.0
	p.gravity = Vector2(0, -7)
	p.initial_velocity_min = 6.0
	p.initial_velocity_max = 22.0
	p.scale_amount_min = 0.4
	p.scale_amount_max = 1.3
	var g := Gradient.new()
	g.set_color(0, Color(1, 0.86, 0.6, 0.0))
	g.set_color(1, Color(0.7, 0.6, 1.0, 0.0))
	g.add_point(0.3, Color(1, 0.88, 0.62, 0.7))
	g.add_point(0.7, Color(0.78, 0.62, 1.0, 0.5))
	p.color_ramp = g
	var m := CanvasItemMaterial.new()
	m.blend_mode = CanvasItemMaterial.BLEND_MODE_ADD
	p.material = m
	p.emitting = true
	add_child(p)


func _make_birds() -> void:
	var bt := _tex("bird")
	if bt == null:
		return
	var rng := RandomNumberGenerator.new()
	rng.seed = 91
	for i in 3:
		var b := Sprite2D.new()
		b.texture = bt
		b.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST
		b.scale = Vector2(2.4, 2.4)
		b.modulate = Color(1, 1, 1, 0.8)
		b.z_index = -135
		add_child(b)
		_fly_bird(b, rng, float(i) * 6.0 + rng.randf_range(0.0, 4.0))


func _fly_bird(b: Sprite2D, rng: RandomNumberGenerator, delay: float) -> void:
	var dur := rng.randf_range(16.0, 24.0)
	var t := create_tween().set_loops()
	t.tween_interval(delay)
	t.tween_callback(func(): b.position = Vector2(-60, rng.randf_range(70, 230)))
	t.tween_property(b, "position:x", W + 80, dur).set_trans(Tween.TRANS_LINEAR)
	t.tween_interval(rng.randf_range(5.0, 10.0))


func _make_hero() -> void:
	hero = Sprite2D.new()
	hero.texture = _tex("hero")
	if hero.texture == null:
		return
	hero.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST
	hero.scale = Vector2(3.2, 3.2)
	hero.position = Vector2(W / 2, H - 70)
	hero.z_index = -80
	add_child(hero)
	var bob := create_tween().set_loops()
	bob.tween_property(hero, "position:y", H - 78, 1.6).set_trans(Tween.TRANS_SINE)
	bob.tween_property(hero, "position:y", H - 70, 1.6).set_trans(Tween.TRANS_SINE)


# ------------------------------------------------------------- menu buttons --
func _build_buttons() -> void:
	var bw := 440.0
	var bh := 54.0
	var gap := 14.0
	var y0 := 300.0
	for i in ENTRIES.size():
		var e: Dictionary = ENTRIES[i]
		var accent := Color(e.color)
		var root := Control.new()
		root.size = Vector2(bw, bh)
		root.position = Vector2(W / 2 - bw / 2, y0 + i * (bh + gap))
		root.pivot_offset = Vector2(bw / 2, bh / 2)
		root.mouse_filter = Control.MOUSE_FILTER_STOP
		content.add_child(root)

		var frame := _nine("btn", 14)
		frame.size = Vector2(bw, bh)
		frame.mouse_filter = Control.MOUSE_FILTER_IGNORE
		root.add_child(frame)

		var hi := _nine("btn_hi", 14)
		hi.size = Vector2(bw, bh)
		hi.mouse_filter = Control.MOUSE_FILTER_IGNORE
		hi.modulate.a = 0.0
		root.add_child(hi)

		# a domain-coloured gem on the left and a mirrored one on the right
		var gem := _label(24, HORIZONTAL_ALIGNMENT_CENTER)
		gem.text = "◆"
		gem.position = Vector2(28, bh / 2 - 20)
		gem.size = Vector2(26, 40)
		gem.add_theme_color_override("font_color", accent)
		gem.modulate.a = 0.5
		root.add_child(gem)

		var gem2 := _label(24, HORIZONTAL_ALIGNMENT_CENTER)
		gem2.text = "◆"
		gem2.position = Vector2(bw - 54, bh / 2 - 20)
		gem2.size = Vector2(26, 40)
		gem2.add_theme_color_override("font_color", accent)
		gem2.modulate.a = 0.5
		root.add_child(gem2)

		var lbl := _label(33, HORIZONTAL_ALIGNMENT_CENTER)
		lbl.text = e.label
		lbl.anchor_right = 1.0; lbl.anchor_bottom = 1.0
		lbl.vertical_alignment = VERTICAL_ALIGNMENT_CENTER
		root.add_child(lbl)

		var arrow := _label(28, HORIZONTAL_ALIGNMENT_CENTER)
		arrow.text = "▸"
		arrow.position = Vector2(72, bh / 2 - 21)
		arrow.size = Vector2(26, 42)
		arrow.add_theme_color_override("font_color", accent)
		arrow.modulate.a = 0.0
		root.add_child(arrow)

		root.modulate.a = 0.0
		var idx := i
		root.mouse_entered.connect(func(): _select(idx))
		root.gui_input.connect(func(ev): _button_input(ev, idx))
		buttons.append({"root": root, "frame": frame, "hi": hi, "label": lbl,
			"arrow": arrow, "gem": gem, "gem2": gem2, "fn": e.fn})


func _nine(name: String, margin: int) -> NinePatchRect:
	var n := NinePatchRect.new()
	n.texture = _tex(name)
	n.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST
	n.patch_margin_left = margin
	n.patch_margin_top = margin
	n.patch_margin_right = margin
	n.patch_margin_bottom = margin
	return n


func _button_input(ev: InputEvent, idx: int) -> void:
	if ev is InputEventMouseButton and ev.pressed and ev.button_index == MOUSE_BUTTON_LEFT:
		_select(idx)
		_activate()


func _select(idx: int) -> void:
	if not ready_for_input or info_open:
		return
	if idx == selected and buttons[idx].hi.modulate.a > 0.5:
		return
	selected = idx
	for i in buttons.size():
		var b: Dictionary = buttons[i]
		var on := (i == selected)
		var t := create_tween().set_parallel(true)
		t.tween_property(b.hi, "modulate:a", 1.0 if on else 0.0, 0.14)
		t.tween_property(b.arrow, "modulate:a", 1.0 if on else 0.0, 0.14)
		t.tween_property(b.gem, "modulate:a", 1.0 if on else 0.5, 0.14)
		t.tween_property(b.gem2, "modulate:a", 1.0 if on else 0.5, 0.14)
		t.tween_property(b.root, "scale", Vector2(1.05, 1.05) if on else Vector2.ONE, 0.14) \
			.set_trans(Tween.TRANS_BACK).set_ease(Tween.EASE_OUT)
		b.label.add_theme_color_override("font_color", Color("fff4d2") if on else Color("d8c9e8"))


func _activate() -> void:
	if not ready_for_input or info_open:
		return
	var b: Dictionary = buttons[selected]
	# quick press feedback then run
	var t := create_tween()
	t.tween_property(b.root, "scale", Vector2(0.97, 0.97), 0.06)
	t.tween_property(b.root, "scale", Vector2(1.05, 1.05), 0.08)
	call(b.fn)


# ------------------------------------------------------------- info overlay --
# A framed window with an ornate header nameplate; the body is rebuilt per view
# (a keycap grid for Controls, an emblem showcase for About).
func _build_info_overlay() -> void:
	info_root = Control.new()
	info_root.anchor_right = 1.0; info_root.anchor_bottom = 1.0
	info_root.visible = false
	info_root.z_index = 120
	add_child(info_root)

	info_dim = ColorRect.new()
	info_dim.color = Color(0.02, 0.01, 0.06, 0.66)
	info_dim.anchor_right = 1.0; info_dim.anchor_bottom = 1.0
	info_dim.mouse_filter = Control.MOUSE_FILTER_STOP
	info_root.add_child(info_dim)

	info_panel = _nine("panel", 16)
	info_panel.size = Vector2(916, 548)
	info_panel.position = Vector2(W / 2 - 458, H / 2 - 274)
	info_panel.pivot_offset = Vector2(458, 274)
	info_root.add_child(info_panel)

	# ornate header nameplate straddling the panel's top edge
	var hw := 460.0
	info_header = TextureRect.new()
	info_header.texture = _tex("title_banner")
	_place_banner(info_header, hw, (W - hw) / 2.0, 18.0)
	info_root.add_child(info_header)

	# title centred inside the header banner's open panel (font fitted on open)
	var hir := _banner_inner(info_header)
	info_title = _label(44, HORIZONTAL_ALIGNMENT_CENTER)
	info_title.position = hir.position
	info_title.size = hir.size
	info_root.add_child(info_title)

	# the body holder (full-rect so child sprites can use screen coordinates)
	info_content = Control.new()
	info_content.anchor_right = 1.0; info_content.anchor_bottom = 1.0
	info_content.mouse_filter = Control.MOUSE_FILTER_IGNORE
	info_root.add_child(info_content)

	info_hint = _label(22, HORIZONTAL_ALIGNMENT_CENTER)
	info_hint.text = "▸  Press SPACE or ESC to go back"
	info_hint.position = Vector2(W / 2 - 420, 552)
	info_hint.size = Vector2(840, 34)
	info_hint.add_theme_color_override("font_color", Color("ffd07a"))
	info_root.add_child(info_hint)


func _clear_info_content() -> void:
	for ch in info_content.get_children():
		ch.queue_free()


# a small keyboard-style cap (reuses the menu button art) sized to its text
func _keycap(txt: String) -> Control:
	var fnt: Font = custom_font if custom_font else ThemeDB.fallback_font
	var tw: float = fnt.get_string_size(txt, HORIZONTAL_ALIGNMENT_LEFT, -1, 24).x
	var w: float = maxf(42.0, tw + 30.0)
	var cap := _nine("btn_hi", 14)
	cap.size = Vector2(w, 44)
	cap.mouse_filter = Control.MOUSE_FILTER_IGNORE
	cap.set_meta("w", w)
	var lbl := _label(24, HORIZONTAL_ALIGNMENT_CENTER)
	lbl.text = txt
	lbl.size = Vector2(w, 44)
	lbl.position = Vector2(0, -2)
	lbl.add_theme_color_override("font_color", Color("fff4d2"))
	cap.add_child(lbl)
	return cap


func _open_info(accent: Color) -> void:
	info_open = true
	info_title.add_theme_color_override("font_color", accent)
	info_root.visible = true
	info_root.modulate.a = 0.0
	info_panel.scale = Vector2(0.9, 0.9)
	info_header.scale = Vector2(0.9, 0.9)
	info_header.pivot_offset = info_header.size / 2.0
	var t := create_tween().set_parallel(true)
	t.tween_property(info_root, "modulate:a", 1.0, 0.22)
	t.tween_property(content, "modulate:a", 0.0, 0.22)      # tuck the menu away
	t.tween_property(info_panel, "scale", Vector2.ONE, 0.30) \
		.set_trans(Tween.TRANS_BACK).set_ease(Tween.EASE_OUT)
	t.tween_property(info_header, "scale", Vector2.ONE, 0.34) \
		.set_trans(Tween.TRANS_BACK).set_ease(Tween.EASE_OUT)


# Controls — a tidy two-column grid of action labels + keyboard caps
func _show_controls() -> void:
	_clear_info_content()
	info_title.text = "Controls"
	var cx := W / 2
	# six rows, centred in the panel body (below the header, above the hint)
	var row := 54.0
	var y := 190.0
	for entry in IMPORTANT_CONTROLS:
		var key: String = entry.keys if entry.has("keys") else _action_key(str(entry.action), str(entry.fallback))
		var al := _label(27, HORIZONTAL_ALIGNMENT_RIGHT)
		al.text = entry.label
		al.position = Vector2(cx - 420, y)
		al.size = Vector2(380, 44)
		al.add_theme_color_override("font_color", Color("cdbfe6"))
		info_content.add_child(al)

		var kx := cx + 20.0
		for tok in key.split(" ", false):
			if tok == "/":
				var sep := _label(24, HORIZONTAL_ALIGNMENT_CENTER)
				sep.text = "/"
				sep.position = Vector2(kx, y)
				sep.size = Vector2(20, 44)
				sep.add_theme_color_override("font_color", Color("9b8fbf"))
				info_content.add_child(sep)
				kx += 24
			else:
				var cap := _keycap(tok)
				cap.position = Vector2(kx, y)
				info_content.add_child(cap)
				kx += float(cap.get_meta("w")) + 8
		y += row
	_open_info(ACCENT["Engineering"])


# About — a short blurb, the five realm emblems, then the credits
func _show_about() -> void:
	_clear_info_content()
	info_title.text = "About"
	var cx := W / 2

	var blurb := RichTextLabel.new()
	blurb.bbcode_enabled = true
	blurb.scroll_active = false
	blurb.fit_content = false
	blurb.position = Vector2(cx - 380, 160)
	blurb.size = Vector2(760, 110)
	blurb.add_theme_font_size_override("normal_font_size", 25)
	blurb.add_theme_constant_override("line_separation", 8)
	blurb.add_theme_color_override("default_color", Color("ece2cf"))
	if custom_font:
		blurb.add_theme_font_override("normal_font", custom_font)
		blurb.add_theme_font_override("bold_font", custom_font)
	blurb.text = ("[center]A quest-based adventure across five career realms. "
		+ "Complete quests, earn stars, and restore each realm by solving its challenges.[/center]")
	info_content.add_child(blurb)

	# the five realm emblems in a row, each with a glowing halo + name
	for i in DOMAINS.size():
		var ex: float = lerp(cx - 300.0, cx + 300.0, i / 4.0)
		var ey := 332.0
		var ac: Color = ACCENT[DOMAINS[i]]
		var halo := TextureRect.new()
		halo.texture = _tex("glow")
		halo.expand_mode = TextureRect.EXPAND_IGNORE_SIZE
		halo.stretch_mode = TextureRect.STRETCH_SCALE
		halo.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST
		halo.size = Vector2(96, 96)
		halo.position = Vector2(ex - 48, ey - 48)
		halo.modulate = Color(ac.r, ac.g, ac.b, 0.5)
		var hm := CanvasItemMaterial.new()
		hm.blend_mode = CanvasItemMaterial.BLEND_MODE_ADD
		halo.material = hm
		info_content.add_child(halo)

		var sp := TextureRect.new()
		sp.texture = _tex("emblem_" + DOMAINS[i].to_lower())
		sp.expand_mode = TextureRect.EXPAND_IGNORE_SIZE
		sp.stretch_mode = TextureRect.STRETCH_KEEP_ASPECT_CENTERED
		sp.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST
		sp.size = Vector2(56, 56)
		sp.position = Vector2(ex - 28, ey - 28)
		info_content.add_child(sp)

		var nm := _label(18, HORIZONTAL_ALIGNMENT_CENTER)
		nm.text = DOMAINS[i]
		nm.position = Vector2(ex - 80, ey + 34)
		nm.size = Vector2(160, 26)
		nm.add_theme_color_override("font_color", ac)
		info_content.add_child(nm)

	var credits := RichTextLabel.new()
	credits.bbcode_enabled = true
	credits.scroll_active = false
	credits.fit_content = false
	credits.position = Vector2(cx - 380, 426)
	credits.size = Vector2(760, 110)
	credits.add_theme_font_size_override("normal_font_size", 23)
	credits.add_theme_constant_override("line_separation", 7)
	credits.add_theme_color_override("default_color", Color("ece2cf"))
	if custom_font:
		credits.add_theme_font_override("normal_font", custom_font)
		credits.add_theme_font_override("bold_font", custom_font)
	credits.text = ("[center][color=#ffd07a]Created by[/color]\n"
		+ "Owen Liu    •    Ryan Tang    •    Jathon Chen\n"
		+ "[font_size=18][color=#b7abd0]Made with the Godot Engine[/color][/font_size][/center]")
	info_content.add_child(credits)
	_open_info(ACCENT["Leadership"])


func _hide_info() -> void:
	var t := create_tween().set_parallel(true)
	t.tween_property(info_root, "modulate:a", 0.0, 0.18)
	t.tween_property(content, "modulate:a", 1.0, 0.22)
	await t.finished
	info_root.visible = false
	info_open = false


# ================================================================ sequencing =
func _intro_animation() -> void:
	# fade up from black, then stage the UI in
	var t := create_tween()
	t.tween_property(fade_overlay, "modulate:a", 0.0, 1.2).set_ease(Tween.EASE_IN_OUT)
	await t.finished

	if is_instance_valid(rift):
		var rt := create_tween()
		rt.tween_property(rift, "modulate:a", 0.95, 1.4)

	var banner: TextureRect = content.get_node("Banner")
	var bt := create_tween()
	bt.tween_property(banner, "modulate:a", 1.0, 0.4)
	bt.parallel().tween_property(banner, "scale", Vector2(1.04, 1.04), 0.0)
	banner.scale = Vector2(0.8, 0.8)
	bt.parallel().tween_property(banner, "scale", Vector2.ONE, 0.6) \
		.set_trans(Tween.TRANS_BACK).set_ease(Tween.EASE_OUT)
	await bt.finished

	var tt := create_tween().set_parallel(true)
	tt.tween_property(title_label, "modulate:a", 1.0, 0.5)
	tt.tween_property(title_glow, "modulate:a", 1.0, 0.6)
	tt.tween_property(subtitle_label, "modulate:a", 1.0, 0.6)
	title_label.scale = Vector2(0.92, 0.92)
	tt.tween_property(title_label, "scale", Vector2.ONE, 0.5) \
		.set_trans(Tween.TRANS_BACK).set_ease(Tween.EASE_OUT)
	await tt.finished

	# logo breathing + glow shimmer loops
	var breathe := create_tween().set_loops()
	breathe.tween_property(title_label, "scale", Vector2(1.025, 1.025), 2.6).set_trans(Tween.TRANS_SINE)
	breathe.tween_property(title_label, "scale", Vector2.ONE, 2.6).set_trans(Tween.TRANS_SINE)
	var shimmer := create_tween().set_loops()
	shimmer.tween_property(title_glow, "modulate:a", 0.45, 1.8).set_trans(Tween.TRANS_SINE)
	shimmer.tween_property(title_glow, "modulate:a", 1.0, 1.8).set_trans(Tween.TRANS_SINE)

	# emblems pop in one by one, their halos blooming with them
	for i in emblem_sprites.size():
		var sp: Sprite2D = emblem_sprites[i]
		sp.scale = Vector2(0.2, 0.2)
		var et := create_tween().set_parallel(true)
		et.tween_property(sp, "modulate:a", 1.0, 0.3)
		et.tween_property(sp, "scale", Vector2(0.95, 0.95), 0.45) \
			.set_trans(Tween.TRANS_BACK).set_ease(Tween.EASE_OUT)
		var halo = sp.get_meta("halo")
		if is_instance_valid(halo):
			create_tween().tween_property(halo, "modulate:a", 0.5, 0.55)
		await get_tree().create_timer(0.08).timeout

	# buttons slide up + fade in
	for i in buttons.size():
		var b: Dictionary = buttons[i]
		var root: Control = b.root
		var fy := root.position.y
		root.position.y = fy + 26
		var bt2 := create_tween().set_parallel(true)
		bt2.tween_property(root, "modulate:a", 1.0, 0.34)
		bt2.tween_property(root, "position:y", fy, 0.4).set_trans(Tween.TRANS_CUBIC).set_ease(Tween.EASE_OUT)
		await get_tree().create_timer(0.07).timeout

	var nav: Label = content.get_node("NavHint")
	var nt := create_tween().set_loops()
	nav.modulate.a = 0.0
	create_tween().tween_property(nav, "modulate:a", 0.85, 0.5)
	nt.tween_property(nav, "modulate:a", 0.4, 1.1).set_trans(Tween.TRANS_SINE)
	nt.tween_property(nav, "modulate:a", 0.85, 1.1).set_trans(Tween.TRANS_SINE)

	ready_for_input = true
	selected = -1
	_select(0)


# ===================================================================== input =
func _unhandled_input(event: InputEvent) -> void:
	if info_open:
		if event.is_action_pressed("ui_accept") or event.is_action_pressed("ui_cancel"):
			_hide_info()
			get_viewport().set_input_as_handled()
		elif event is InputEventKey and event.pressed and not event.echo and event.keycode == KEY_SPACE:
			_hide_info()
			get_viewport().set_input_as_handled()
		return

	if not ready_for_input:
		return
	if event.is_action_pressed("ui_down"):
		_select((selected + 1) % buttons.size())
		get_viewport().set_input_as_handled()
	elif event.is_action_pressed("ui_up"):
		_select((selected - 1 + buttons.size()) % buttons.size())
		get_viewport().set_input_as_handled()
	elif event.is_action_pressed("ui_accept"):
		_activate()
		get_viewport().set_input_as_handled()


# =================================================================== actions =
func _on_new_game() -> void:
	ready_for_input = false
	var t := create_tween()
	t.tween_property(fade_overlay, "modulate:a", 1.0, 0.9).set_ease(Tween.EASE_IN)
	await t.finished
	get_tree().change_scene_to_file("res://scenes/intro/IntroCutscene.tscn")


func _on_controls() -> void:
	_show_controls()


func _on_credits() -> void:
	_show_about()


func _on_exit() -> void:
	ready_for_input = false
	var t := create_tween()
	t.tween_property(fade_overlay, "modulate:a", 1.0, 0.5)
	await t.finished
	get_tree().quit()


func _action_key(action_name: String, fallback: String) -> String:
	if not InputMap.has_action(action_name):
		return fallback
	for event in InputMap.action_get_events(action_name):
		if event is InputEventKey:
			var kc: Key = event.physical_keycode if event.physical_keycode != 0 else event.keycode
			if kc != 0:
				var nm := OS.get_keycode_string(kc)
				if nm != "":
					return nm
	return fallback
